// Copyright 2026 Lusoris
// SPDX-License-Identifier: EUPL-1.2

// Package bpf provides the Go-side loader for the rclone FUSE bypass eBPF
// program (ADR-0779).
//
// When the node enables it (VMAFX_EBPF_BYPASS, cmd/vmafx-node/ebpf_linux.go),
// the loader:
//  1. Checks the host (Preflight: kernel, BTF, capabilities) and the prefix.
//  2. Loads the BPF object bpf2go generated and embedded (rclonebypass_bpfel.o).
//  3. Writes the mount prefix into the mount_prefix_map.
//  4. Attaches tracepoints for openat/close.
//  5. Reads ring-buffer events to populate an in-process cache of descriptors
//     opened under the prefix (IsBypassFD, TrackedFDs).
//
// The loader tracks descriptors; it does not change any read. ADR-0779's
// read-path bypass (pread on a backing cache file instead of the FUSE path)
// has no consumer: the vmaf CLI, a separate process, reads the mounted files,
// and pkg/storage mounts with --vfs-cache-mode off, so no backing cache file
// exists (ADR-1539). No kernel memory is modified.
//
// Kernel version requirement: Linux 5.15+ (BPF CO-RE, ring buffer, bpf_d_path).
// Capability requirement: CAP_BPF (Linux 5.8+) or CAP_SYS_ADMIN.
// Container requirement: --privileged or securityContext.privileged=true + mounted
// /sys/kernel/btf/vmlinux.
//
// ADR-0779.
package bpf

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"strings"
	"sync"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

const (
	// DefaultMountPrefix is the FUSE mount point watched by default.
	DefaultMountPrefix = "/rclone-mount/"

	maxPathLen = 256

	// maxTrackedFDs mirrors MAX_TRACKED_FDS, the size of the bypass_fds map.
	// The Go cache prunes descriptors the kernel side has dropped (closed)
	// when it reaches this size, so it cannot grow without bound.
	maxTrackedFDs = 4096
)

// BypassEntry describes a bypass-eligible open file descriptor.
type BypassEntry struct {
	FdKey uint64 // (pid << 32) | fd
	Path  string // path that was opened
}

// Loader manages the lifecycle of the eBPF bypass program.
type Loader struct {
	mu          sync.RWMutex
	objs        rcloneBypassObjects // generated by bpf2go
	links       []link.Link
	ringReader  *ringbuf.Reader
	activeFDs   map[uint64]string // fd_key → path
	mountPrefix string
	log         *slog.Logger
}

// New creates a Loader.  The eBPF program is NOT loaded until Start is called.
func New(mountPrefix string, log *slog.Logger) *Loader {
	if mountPrefix == "" {
		mountPrefix = DefaultMountPrefix
	}
	if !strings.HasSuffix(mountPrefix, "/") {
		mountPrefix += "/"
	}
	if log == nil {
		log = slog.Default()
	}
	return &Loader{
		mountPrefix: mountPrefix,
		activeFDs:   make(map[uint64]string),
		log:         log,
	}
}

// Start loads and attaches the eBPF program.  Returns an error if the kernel
// does not support the required features or the process lacks privileges;
// Preflight names those before any BPF syscall is made. ctx bounds the
// ring-buffer drain goroutine, so it must live as long as the loader.
func (l *Loader) Start(ctx context.Context) error {
	if err := validatePrefix(l.mountPrefix); err != nil {
		return err
	}
	if err := preflight(); err != nil {
		return err
	}
	// Remove the default locked memory limit so BPF maps can be allocated.
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("ebpf: remove memlock: %w", err)
	}

	// Load pre-compiled BPF objects (generated by bpf2go; embedded in binary).
	if err := loadRcloneBypassObjects(&l.objs, nil); err != nil {
		return fmt.Errorf("ebpf: load objects: %w", err)
	}

	// Write mount prefix into the BPF map.
	if err := l.writeMountPrefix(); err != nil {
		l.closeObjects()
		return fmt.Errorf("ebpf: write mount prefix: %w", err)
	}

	// Attach tracepoints.
	if err := l.attachTracepoints(); err != nil {
		l.closeLinks()
		l.closeObjects()
		return err
	}

	// Open ring-buffer reader.
	rd, err := ringbuf.NewReader(l.objs.Events)
	if err != nil {
		l.closeLinks()
		l.closeObjects()
		return fmt.Errorf("ebpf: ring buffer: %w", err)
	}
	l.ringReader = rd

	// Drain ring buffer in background goroutine.
	go l.drainLoop(ctx)

	l.log.Info("ebpf bypass active",
		"mount_prefix", l.mountPrefix,
		"kernel_min", "5.15")
	return nil
}

// tracepointSpec names one kernel tracepoint and the loaded BPF program to attach to it.
type tracepointSpec struct {
	group   string
	name    string
	program *ebpf.Program
}

// attachTracepoints attaches every tracepoint the bypass program needs, in the order the
// kernel-side program expects them, appending each successful link to l.links.
//
// On failure the links attached so far stay in l.links, so the caller's closeLinks
// releases exactly the set the inline sequence used to release, in the same order.
func (l *Loader) attachTracepoints() error {
	specs := [...]tracepointSpec{
		{"syscalls", "sys_enter_openat", l.objs.TpOpenatEnter},
		{"syscalls", "sys_exit_openat", l.objs.TpOpenatExit},
		{"syscalls", "sys_enter_close", l.objs.TpCloseEnter},
	}
	for _, spec := range specs {
		lk, err := link.Tracepoint(spec.group, spec.name, spec.program, nil)
		if err != nil {
			return fmt.Errorf("ebpf: attach %s: %w", spec.name, err)
		}
		l.links = append(l.links, lk)
	}
	return nil
}

// closeObjects releases the loaded BPF collection.
//
// Every caller either already carries a more specific error back to its own caller or is
// shutting the loader down, so a failure to release the collection is recorded on the
// loader's log rather than returned.
func (l *Loader) closeObjects() {
	if err := l.objs.Close(); err != nil {
		l.log.Warn("ebpf: close objects failed", "err", err)
	}
}

// Stop detaches all eBPF probes and frees resources.
func (l *Loader) Stop() {
	if l.ringReader != nil {
		if err := l.ringReader.Close(); err != nil {
			l.log.Warn("ebpf: close ring buffer reader failed", "err", err)
		}
	}
	l.closeLinks()
	l.closeObjects()
	l.log.Info("ebpf bypass stopped")
}

// IsBypassFD returns true if the given (pid, fd) pair is bypass-eligible.
func (l *Loader) IsBypassFD(pid uint32, fd uint32) (string, bool) {
	fdKey := (uint64(pid) << 32) | uint64(fd)
	l.mu.RLock()
	path, ok := l.activeFDs[fdKey]
	l.mu.RUnlock()
	return path, ok
}

// validatePrefix refuses a prefix the BPF side would not match as given: it
// must be absolute and fit mount_prefix_t (255 bytes plus the terminator).
// A longer prefix used to be truncated silently.
func validatePrefix(prefix string) error {
	if !strings.HasPrefix(prefix, "/") {
		return fmt.Errorf("ebpf: mount prefix %q must be an absolute path", prefix)
	}
	if len(prefix) > maxPathLen-1 {
		return fmt.Errorf("ebpf: mount prefix is %d bytes, the BPF program matches at most %d", len(prefix), maxPathLen-1)
	}
	return nil
}

// writeMountPrefix stores the mount prefix into the BPF array map at index 0.
// rcloneBypassMountPrefixT is bpf2go's mirror of struct mount_prefix_t, so its
// size is the map's value size (260 bytes; a hand-written mirror with explicit
// padding was 264 and would have been rejected by the kernel).
func (l *Loader) writeMountPrefix() error {
	var mp rcloneBypassMountPrefixT
	for i := range len(l.mountPrefix) {
		mp.Prefix[i] = int8(l.mountPrefix[i]) // #nosec G115 -- byte reinterpreted as C char
	}
	mp.PrefixLen = uint32(len(l.mountPrefix)) // #nosec G115 -- validatePrefix bounds it to 255
	return l.objs.MountPrefixMap.Update(uint32(0), &mp, ebpf.UpdateAny)
}

// drainLoop reads ring-buffer events and updates the in-process FD cache.
// The loop runs until the context is cancelled or the ring buffer is closed; ctx.Err()
// is the same edge the pre-loop select used to test, hoisted into the loop condition so
// the exit condition is stated where the loop is entered. A context without a Done
// channel reports a nil Err forever, which is the never-cancelled case the select's
// default branch covered.
func (l *Loader) drainLoop(ctx context.Context) {
	for ctx.Err() == nil {
		rec, err := l.ringReader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return
			}
			l.log.Warn("ebpf ring buffer read error", "err", err)
			continue
		}

		fdKey, path, ok := decodeEvent(rec.RawSample)
		if !ok {
			continue
		}

		l.mu.Lock()
		if len(l.activeFDs) >= maxTrackedFDs {
			l.pruneClosedLocked()
		}
		l.activeFDs[fdKey] = path
		l.mu.Unlock()

		l.log.Debug("ebpf bypass: new eligible FD",
			"fd_key", fdKey, "path", path)
	}
}

// decodeEvent decodes one ring-buffer record into bpf2go's mirror of struct
// event_t. A record shorter than the struct is truncated and dropped; the path
// ends at its first NUL or at maxPathLen.
func decodeEvent(raw []byte) (uint64, string, bool) {
	var ev rcloneBypassEventT
	if err := binary.Read(bytes.NewReader(raw), binary.NativeEndian, &ev); err != nil {
		return 0, "", false
	}
	path := make([]byte, 0, maxPathLen)
	for _, c := range ev.Path {
		if c == 0 {
			break
		}
		path = append(path, byte(c)) // #nosec G115 -- C char reinterpreted as the byte it holds
	}
	return ev.FdKey, string(path), true
}

// pruneClosedLocked drops cached descriptors the kernel side no longer holds:
// tp_close_enter deletes a closed descriptor from bypass_fds, but the ring
// buffer reports opens only. Called with l.mu held; bounded by maxTrackedFDs.
func (l *Loader) pruneClosedLocked() {
	var entry rcloneBypassBypassEntryT
	for key := range l.activeFDs {
		if err := l.objs.BypassFds.Lookup(key, &entry); err != nil {
			delete(l.activeFDs, key)
		}
	}
}

// TrackedFDs reports how many bypass-eligible descriptors the cache holds.
func (l *Loader) TrackedFDs() int {
	l.mu.RLock()
	defer l.mu.RUnlock()
	return len(l.activeFDs)
}

// MountPrefix returns the normalised prefix the loader watches.
func (l *Loader) MountPrefix() string { return l.mountPrefix }

// closeLinks detaches every attached probe and clears the link set.
//
// Detach failures are recorded rather than returned: the loop must keep going so a single
// stuck probe cannot strand the ones after it, and both callers (Start's unwind and Stop)
// have no error channel left to use.
func (l *Loader) closeLinks() {
	for _, lk := range l.links {
		if err := lk.Close(); err != nil {
			l.log.Warn("ebpf: detach probe failed", "err", err)
		}
	}
	l.links = nil
}

// Enabled reports whether the eBPF bypass feature flag is set.
// Returns true when VMAFX_EBPF_BYPASS=1.
func Enabled() bool {
	return os.Getenv("VMAFX_EBPF_BYPASS") == "1"
}
