// Copyright 2026 Lusoris
// SPDX-License-Identifier: EUPL-1.2

// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type rcloneBypassBypassEntryT struct {
	_            structs.HostLayout
	BackingInode uint64
	Flags        uint32
	Active       uint8
	_            [3]byte
}

type rcloneBypassEventT struct {
	_       structs.HostLayout
	PidTgid uint64
	FdKey   uint64
	Inode   uint64
	Path    [256]int8
}

type rcloneBypassMountPrefixT struct {
	_         structs.HostLayout
	Prefix    [256]int8
	PrefixLen uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	rcloneBypassMapBypassFds      = "bypass_fds"
	rcloneBypassMapEvents         = "events"
	rcloneBypassMapMountPrefixMap = "mount_prefix_map"
	rcloneBypassMapScratchPaths   = "scratch_paths"
	rcloneBypassProgTpCloseEnter  = "tp_close_enter"
	rcloneBypassProgTpOpenatEnter = "tp_openat_enter"
	rcloneBypassProgTpOpenatExit  = "tp_openat_exit"
	rcloneBypassVarUnusedEventT   = "unused_event_t"
)

// loadRcloneBypass returns the embedded CollectionSpec for rcloneBypass.
func loadRcloneBypass() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RcloneBypassBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rcloneBypass: %w", err)
	}

	return spec, err
}

// loadRcloneBypassObjects loads rcloneBypass and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rcloneBypassObjects
//	*rcloneBypassPrograms
//	*rcloneBypassMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRcloneBypassObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadRcloneBypass()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rcloneBypassSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rcloneBypassSpecs struct {
	rcloneBypassProgramSpecs
	rcloneBypassMapSpecs
	rcloneBypassVariableSpecs
}

// rcloneBypassProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rcloneBypassProgramSpecs struct {
	TpCloseEnter  *ebpf.ProgramSpec `ebpf:"tp_close_enter"`
	TpOpenatEnter *ebpf.ProgramSpec `ebpf:"tp_openat_enter"`
	TpOpenatExit  *ebpf.ProgramSpec `ebpf:"tp_openat_exit"`
}

// rcloneBypassMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rcloneBypassMapSpecs struct {
	BypassFds      *ebpf.MapSpec `ebpf:"bypass_fds"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	MountPrefixMap *ebpf.MapSpec `ebpf:"mount_prefix_map"`
	ScratchPaths   *ebpf.MapSpec `ebpf:"scratch_paths"`
}

// rcloneBypassVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rcloneBypassVariableSpecs struct {
	UnusedEventT *ebpf.VariableSpec `ebpf:"unused_event_t"`
}

// rcloneBypassObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRcloneBypassObjects or ebpf.CollectionSpec.LoadAndAssign.
type rcloneBypassObjects struct {
	rcloneBypassPrograms
	rcloneBypassMaps
	rcloneBypassVariables
}

func (o *rcloneBypassObjects) Close() error {
	return _RcloneBypassClose(
		&o.rcloneBypassPrograms,
		&o.rcloneBypassMaps,
	)
}

// rcloneBypassMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRcloneBypassObjects or ebpf.CollectionSpec.LoadAndAssign.
type rcloneBypassMaps struct {
	BypassFds      *ebpf.Map `ebpf:"bypass_fds"`
	Events         *ebpf.Map `ebpf:"events"`
	MountPrefixMap *ebpf.Map `ebpf:"mount_prefix_map"`
	ScratchPaths   *ebpf.Map `ebpf:"scratch_paths"`
}

func (m *rcloneBypassMaps) Close() error {
	return _RcloneBypassClose(
		m.BypassFds,
		m.Events,
		m.MountPrefixMap,
		m.ScratchPaths,
	)
}

// rcloneBypassVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRcloneBypassObjects or ebpf.CollectionSpec.LoadAndAssign.
type rcloneBypassVariables struct {
	UnusedEventT *ebpf.Variable `ebpf:"unused_event_t"`
}

// rcloneBypassPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRcloneBypassObjects or ebpf.CollectionSpec.LoadAndAssign.
type rcloneBypassPrograms struct {
	TpCloseEnter  *ebpf.Program `ebpf:"tp_close_enter"`
	TpOpenatEnter *ebpf.Program `ebpf:"tp_openat_enter"`
	TpOpenatExit  *ebpf.Program `ebpf:"tp_openat_exit"`
}

func (p *rcloneBypassPrograms) Close() error {
	return _RcloneBypassClose(
		p.TpCloseEnter,
		p.TpOpenatEnter,
		p.TpOpenatExit,
	)
}

func _RcloneBypassClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rclonebypass_bpfel.o
var _RcloneBypassBytes []byte
