// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

package obsgen

import (
	"fmt"
	"strings"
)

// The Helm chart's generated files: the PrometheusRule template, the copies
// of the dashboards its ConfigMaps read (Helm reads no file outside the
// chart), and the settings block of its values.yaml.
const (
	HelmChartDir     = "deploy/helm/vmafx"
	HelmRuleTemplate = HelmChartDir + "/templates/prometheusrule.yaml"
	HelmDashboardDir = HelmChartDir + "/files/dashboards"
	HelmValuesFile   = HelmChartDir + "/values.yaml"
	// SettingsRegion names the generated block of HelmValuesFile.
	SettingsRegion = "obsgen monitoring settings"
)

// helmRuleHeader starts the PrometheusRule template.
const helmRuleHeader = `{{- /*
  SPDX-License-Identifier: EUPL-1.2
  Copyright 2026 Lusoris

  GENERATED by tools/obsgen from pkg/observability/obsgen; do not edit.
  Regenerate: go run ./tools/obsgen -write

  The alert and recording rules of deploy/prometheus/vmafx-rules.yaml as a
  PrometheusRule, with the SLO objectives, burn-rate windows and alert
  thresholds read from .Values.monitoring.slo, .burnRates and .alerts.
  Rendered with the default values its groups equal that file's.
*/}}
`

// helmRuleTemplate renders the chart's PrometheusRule template from the rules
// built with helmParams. The SLO recording rules are one rule per ratio,
// wrapped in a range over the configured windows.
func helmRuleTemplate() ([]byte, error) {
	body, err := encodeYAML(ruleFile{Groups: ruleGroups(helmParams())})
	if err != nil {
		return nil, err
	}
	ranged, err := rangeWindows(string(body))
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString(helmRuleHeader)
	b.WriteString("{{- if and " + helmValues + ".enabled " + helmValues + ".prometheusRule.enabled }}\n")
	b.WriteString("{{- $windows := " + helmWindows + " }}\n")
	b.WriteString(`apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "vmafx.fullname" . }}
  namespace: {{ .Values.monitoring.prometheusRule.namespace | default .Release.Namespace }}
  labels:
    {{- include "vmafx.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
`)
	for _, line := range strings.SplitAfter(ranged, "\n") {
		if line != "" {
			b.WriteString("  " + line)
		}
	}
	b.WriteString("{{- end }}\n")
	return []byte(b.String()), nil
}

// rangeWindows wraps every list item of the encoded rules whose record name
// holds helmWindow in a range over $windows: the item's line and its more
// indented continuation lines.
func rangeWindows(body string) (string, error) {
	lines := strings.Split(body, "\n")
	var out []string
	ranged := 0
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		trimmed := strings.TrimLeft(line, " ")
		if !strings.HasPrefix(trimmed, "- record: ") || !strings.Contains(line, helmWindow) {
			out = append(out, line)
			continue
		}
		indent := line[:len(line)-len(trimmed)]
		out = append(out, indent+"{{- range $w := $windows }}", line)
		for i+1 < len(lines) && strings.HasPrefix(lines[i+1], indent+"  ") {
			i++
			out = append(out, lines[i])
		}
		out = append(out, indent+"{{- end }}")
		ranged++
	}
	if want := len(sloRatios(helmParams())); ranged != want {
		return "", fmt.Errorf("obsgen: ranged %d recording rules over the windows, want %d", ranged, want)
	}
	return strings.Join(out, "\n"), nil
}

// settingsValues renders the defaults as the generated block of the chart's
// values.yaml, under monitoring:, with a comment for every key.
func settingsValues(s Settings) []byte {
	var b strings.Builder
	line := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	line("# Generated from obsgen.DefaultSettings by go run ./tools/obsgen -write;")
	line("# change the defaults in pkg/observability/obsgen/settings.go. Override them")
	line("# in your own values file: the PrometheusRule (prometheusRule.enabled) is")
	line("# rendered from them, and the Compose example reads the same keys.")
	line("# slo: the share of events that must be good over 30 days; the error")
	line("# budget is 1 - objective. Each lies strictly between 0 and 1.")
	line("slo:")
	line("  # Controller jobs that complete rather than fail.")
	line("  jobSuccess: %v", s.SLO.JobSuccess)
	line("  # Score requests that return no error.")
	line("  scoreSuccess: %v", s.SLO.ScoreSuccess)
	line("  # Score requests that finish within scoreLatencySeconds.")
	line("  scoreLatency: %v", s.SLO.ScoreLatency)
	line("  # A bucket bound of vmafx_server_score_duration_seconds, quoted.")
	line("  scoreLatencySeconds: %q", s.SLO.ScoreLatencySeconds)
	line("# burnRates: multi-window, multi-burn-rate alerting. A rule fires when the")
	line("# ratio of bad events over longWindow and over shortWindow both exceed")
	line("# factor * (1 - objective) for the for duration. fast is critical, slow a")
	line("# warning. Windows and for are Prometheus durations.")
	line("burnRates:")
	for _, r := range []struct {
		key string
		b   BurnRate
	}{{"fast", s.BurnRates.Fast}, {"slow", s.BurnRates.Slow}} {
		line("  %s:", r.key)
		line("    longWindow: %s", r.b.LongWindow)
		line("    shortWindow: %s", r.b.ShortWindow)
		line("    factor: %v", r.b.Factor)
		line("    for: %s", r.b.For)
	}
	line("# alerts: thresholds of the alerts that are not burn rates.")
	line("alerts:")
	line("  # VMAFxQueueAging: how old, in seconds, a tenant's oldest pending job")
	line("  # may get.")
	line("  queueAgeSeconds: %d", s.Alerts.QueueAgeSeconds)
	line("  # VMAFxScoreRegression: the drop, in score points, of an hour's median")
	line("  # below the median of the previous day's hourly medians.")
	line("  scoreRegressionPoints: %v", s.Alerts.ScoreRegressionPoints)
	line("  # VMAFxScoreRegression: the scores an hour needs to be compared.")
	line("  scoreRegressionMinScores: %d", s.Alerts.ScoreRegressionMinScores)
	line("# cost: the prices of the VMAFx Usage and cost dashboard, the same for")
	line("# every backend. 0 is unset: its cost panels stay empty.")
	line("cost:")
	line("  # Price of one second a node spends on a job.")
	line("  perJobSecond: %v", s.Cost.PerJobSecond)
	line("  # Price of one completed or failed job; cancelled jobs are not charged.")
	line("  perJob: %v", s.Cost.PerJob)
	line("  # ISO 4217 code shown with the costs, or empty.")
	line("  currency: %q", s.Cost.Currency)
	return []byte(b.String())
}
