// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

package obsgen

import (
	"bytes"
	"fmt"
	"path"
	"strings"

	"go.yaml.in/yaml/v3"

	m "github.com/VMAFx/vmafx/pkg/observability/metricdef"
)

// generatedHeader starts every generated YAML file.
const generatedHeader = "# GENERATED by tools/obsgen from pkg/observability/obsgen; do not edit.\n" +
	"# Regenerate: go run ./tools/obsgen -write\n"

type ruleFile struct {
	Groups []ruleGroup `yaml:"groups"`
}

type ruleGroup struct {
	Name  string `yaml:"name"`
	Rules []any  `yaml:"rules"`
}

type alertingRule struct {
	Alert       string            `yaml:"alert"`
	Expr        string            `yaml:"expr"`
	For         string            `yaml:"for"`
	Labels      map[string]string `yaml:"labels"`
	Annotations map[string]string `yaml:"annotations"`
}

// annotations of rule r of alert a, as Prometheus templates.
func annotations(a alert, r alertRule) map[string]string {
	return map[string]string{
		"summary":     r.summary,
		"description": r.description,
		"runbook_url": runbookURL(a.runbook),
	}
}

// RenderRules renders the rule file for s: the recording rules, then the
// alerts. The committed RulesFile is RenderRules(DefaultSettings()).
func RenderRules(s Settings) ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}
	return marshalYAML(ruleFile{Groups: ruleGroups(plainParams(s))})
}

// ruleGroups are the recording rules, then the alerts, rendered with p.
func ruleGroups(p params) []ruleGroup {
	var rec []any
	for _, r := range recordingRules(p) {
		rec = append(rec, r)
	}
	var al []any
	for _, a := range alerts(p) {
		for _, r := range a.rules {
			al = append(al, alertingRule{
				Alert: a.name, Expr: r.expr, For: r.forDur,
				Labels: map[string]string{"severity": r.severity}, Annotations: annotations(a, r),
			})
		}
	}
	return []ruleGroup{
		{Name: "vmafx.recording", Rules: rec},
		{Name: "vmafx.alerts", Rules: al},
	}
}

type ruleTestFile struct {
	RuleFiles          []string   `yaml:"rule_files"`
	EvaluationInterval string     `yaml:"evaluation_interval"`
	Tests              []ruleTest `yaml:"tests"`
}

type ruleTest struct {
	Name           string           `yaml:"name"`
	Interval       string           `yaml:"interval"`
	InputSeries    []inputSeries    `yaml:"input_series"`
	AlertRuleTest  []alertRuleTest  `yaml:"alert_rule_test,omitempty"`
	PromQLExprTest []promQLExprTest `yaml:"promql_expr_test,omitempty"`
}

// promQLExprTest evaluates one expression, here a dashboard query, against
// the input series.
type promQLExprTest struct {
	Expr       string      `yaml:"expr"`
	EvalTime   string      `yaml:"eval_time"`
	ExpSamples []expSample `yaml:"exp_samples"`
}

type expSample struct {
	Labels string  `yaml:"labels"`
	Value  float64 `yaml:"value"`
}

type alertRuleTest struct {
	EvalTime  string     `yaml:"eval_time"`
	Alertname string     `yaml:"alertname"`
	ExpAlerts []expAlert `yaml:"exp_alerts"`
}

type expAlert struct {
	ExpLabels      map[string]string `yaml:"exp_labels"`
	ExpAnnotations map[string]string `yaml:"exp_annotations"`
}

// rulesTestYAML renders the promtool unit test of the rule file: every case
// of every alert, firing ones with the labels and rendered annotations they
// must carry, the others with none.
func rulesTestYAML() ([]byte, error) {
	f := ruleTestFile{RuleFiles: []string{path.Base(RulesFile)}, EvaluationInterval: "1m"}
	for _, a := range alerts(plainParams(DefaultSettings())) {
		for i, c := range a.cases {
			exp, err := expectedAlerts(a, c)
			if err != nil {
				return nil, err
			}
			f.Tests = append(f.Tests, ruleTest{
				Name: fmt.Sprintf("%s case %d", a.name, i+1), Interval: c.interval, InputSeries: c.series,
				AlertRuleTest: []alertRuleTest{{EvalTime: c.evalTime, Alertname: a.name, ExpAlerts: exp}},
			})
		}
	}
	f.Tests = append(f.Tests, dashboardQueryTests()...)
	return marshalYAML(f)
}

// dashboardQueryTests evaluate dashboard queries whose arithmetic a decision
// fixes. The per-job cost charges completed and failed jobs, never cancelled
// ones (Q-208): over an hour a tenant completes 60 jobs, fails 60 and cancels
// 300 at a price of 2, which costs 240, not 840.
func dashboardQueryTests() []ruleTest {
	jobs := func(outcome, values string) inputSeries {
		return series(m.ControllerJobDuration.Name+"_count",
			`job="vmafx-controller",instance="c:8080",tenant="a",outcome="`+outcome+`"`, values)
	}
	return []ruleTest{{
		Name: "per-job cost charges completed and failed jobs, not cancelled ones", Interval: "1m",
		InputSeries: []inputSeries{
			jobs("completed", "0+1x60"), jobs("failed", "0+1x60"), jobs("cancelled", "0+5x60"),
			series(PricePerJob, `job="vmafx-controller",instance="c:8080",currency="XTS"`, "2x60"),
		},
		PromQLExprTest: []promQLExprTest{{
			Expr: Instantiate(PerJobCostQuery("1h"), "1h"), EvalTime: "1h",
			ExpSamples: []expSample{{Labels: `{currency="XTS", tenant="a"}`, Value: 240}},
		}},
	}}
}

// expectedAlerts are the alerts case c expects, the annotations rendered from
// the rule of the same severity.
func expectedAlerts(a alert, c alertCase) ([]expAlert, error) {
	exp := []expAlert{}
	for _, labels := range c.firing {
		r, ok := ruleOfSeverity(a, labels["severity"])
		if !ok {
			return nil, fmt.Errorf("obsgen: %s has no rule of severity %q", a.name, labels["severity"])
		}
		ann := map[string]string{}
		for k, v := range annotations(a, r) {
			ann[k] = renderLabels(v, labels)
		}
		exp = append(exp, expAlert{ExpLabels: labels, ExpAnnotations: ann})
	}
	return exp, nil
}

func ruleOfSeverity(a alert, severity string) (alertRule, bool) {
	for _, r := range a.rules {
		if r.severity == severity {
			return r, true
		}
	}
	return alertRule{}, false
}

// renderLabels expands the {{ $labels.<name> }} references of a template,
// the only template form the generated annotations use.
func renderLabels(tmpl string, labels map[string]string) string {
	for k, v := range labels {
		tmpl = strings.ReplaceAll(tmpl, "{{ $labels."+k+" }}", v)
	}
	return tmpl
}

// marshalYAML encodes v after the generated-file header.
func marshalYAML(v any) ([]byte, error) {
	body, err := encodeYAML(v)
	if err != nil {
		return nil, err
	}
	return append([]byte(generatedHeader), body...), nil
}

// encodeYAML encodes v with two-space indentation.
func encodeYAML(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		return nil, fmt.Errorf("obsgen: encode YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("obsgen: encode YAML: %w", err)
	}
	return buf.Bytes(), nil
}
