# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Protobuf files of the platform definition (ADR-2350 D13).

One file per `[[files]]` entry: its services, then its enums, then its
messages, each in definition order, with the definition's documentation as
comments. A type of another file is imported; a type of another package is
written fully qualified. `buf generate` (scripts/codegen/proto_generate.py)
turns the files into the Go bindings under gen/go.
"""

from __future__ import annotations

import textwrap

from .platform import (
    MAP_TYPE,
    Message,
    MessageField,
    Platform,
    PlatformEnum,
    ProtoFile,
    Rpc,
    Service,
    resolve,
)

WIDTH = 96
HEADER = """// GENERATED by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml (ADR-2350).
// Do not edit: change the definition and run `python3 scripts/codegen/vmafx-api.py --write`,
// then `python3 scripts/codegen/proto_generate.py --write` (gen/go/AGENTS.md).
//
// {spdx}
// Copyright 2026 Lusoris
//
{doc}

syntax = "proto3";

package {package};
"""


def comment(text: str, indent: str = "") -> list[str]:
    """`//` lines of a documentation text; its own line breaks are kept."""
    lines: list[str] = []
    for line in text.splitlines():
        if not line.strip():
            lines.append(f"{indent}//")
            continue
        lead = line[: len(line) - len(line.lstrip())]
        wrapped = textwrap.wrap(line.strip(), width=WIDTH - len(indent) - len(lead) - 3)
        lines += [f"{indent}// {lead}{part}".rstrip() for part in wrapped]
    while lines and lines[0].strip() == "//":
        lines.pop(0)
    return lines


def _type_name(platform: Platform, home: ProtoFile, name: str) -> str:
    _, where = resolve(platform, name)
    if where is None or where.package == home.package:
        return name
    return f"{where.package}.{name}"


def _field_type(platform: Platform, home: ProtoFile, fld: MessageField) -> str:
    match = MAP_TYPE.fullmatch(fld.type)
    if match is not None:
        key, value = match.groups()
        return f"map<{key}, {_type_name(platform, home, value)}>"
    label = "repeated " if fld.repeated else ""
    return label + _type_name(platform, home, fld.type)


def _field_lines(platform: Platform, home: ProtoFile, fld: MessageField, indent: str) -> list[str]:
    kind = _field_type(platform, home, fld)
    return [*comment(fld.doc, indent), f"{indent}{kind} {fld.name} = {fld.number};"]


def _message(platform: Platform, home: ProtoFile, message: Message) -> list[str]:
    if not message.fields:
        return [*comment(message.doc), f"message {message.name} {{}}"]
    lines = [*comment(message.doc), f"message {message.name} {{"]
    done: set[str] = set()
    for i, fld in enumerate(message.fields):
        if fld.oneof in done:
            continue
        lines += [""] if i else []
        if not fld.oneof:
            lines += _field_lines(platform, home, fld, "  ")
            continue
        done.add(fld.oneof)
        members = [f for f in message.fields if f.oneof == fld.oneof]
        lines.append(f"  oneof {fld.oneof} {{")
        for member in members:
            lines += _field_lines(platform, home, member, "    ")
        lines.append("  }")
    return [*lines, "}"]


def _enum(enum: PlatformEnum) -> list[str]:
    lines = [*comment(enum.doc), f"enum {enum.name} {{"]
    for value in enum.values:
        lines += [*comment(value.doc, "  "), f"  {value.name} = {value.number};"]
    return [*lines, "}"]


def _rpc(platform: Platform, home: ProtoFile, rpc: Rpc) -> list[str]:
    request = ("stream " if rpc.client_stream else "") + _type_name(platform, home, rpc.request)
    response = ("stream " if rpc.server_stream else "") + _type_name(platform, home, rpc.response)
    return [*comment(rpc.doc, "  "), f"  rpc {rpc.name}({request}) returns ({response});"]


def _service(platform: Platform, home: ProtoFile, service: Service) -> list[str]:
    lines = [*comment(service.doc), f"service {service.name} {{"]
    for i, rpc in enumerate(service.rpcs):
        lines += ([""] if i else []) + _rpc(platform, home, rpc)
    return [*lines, "}"]


def _referenced(platform: Platform, home: ProtoFile) -> set[str]:
    names: set[str] = set()
    for message in platform.messages:
        if message.file == home.name:
            for fld in message.fields:
                match = MAP_TYPE.fullmatch(fld.type)
                names.add(match.group(2) if match else fld.type)
    for service in platform.services:
        if service.file == home.name:
            names |= {r.request for r in service.rpcs} | {r.response for r in service.rpcs}
    return names


def _imports(platform: Platform, home: ProtoFile) -> list[str]:
    paths = set()
    for name in _referenced(platform, home):
        _, where = resolve(platform, name)
        if where is not None and where.import_path != home.import_path:
            paths.add(where.import_path)
    return [f'import "{p}";' for p in sorted(paths)]


def file_text(platform: Platform, home: ProtoFile) -> str:
    """The text of one generated protobuf file."""
    header = HEADER.format(
        spdx="SPDX-" + "License-Identifier: EUPL-1.2",
        doc="\n".join(comment(home.doc)),
        package=home.package,
    )
    imports = _imports(platform, home)
    head = header + ("\n" + "\n".join(imports) + "\n" if imports else "")
    head += f'\noption go_package = "{home.go_package}";\n'
    blocks = [_service(platform, home, s) for s in platform.services if s.file == home.name]
    blocks += [_enum(e) for e in platform.enums if e.file == home.name]
    blocks += [_message(platform, home, m) for m in platform.messages if m.file == home.name]
    return head + "\n" + "\n\n".join("\n".join(block) for block in blocks) + "\n"


def files(platform: Platform) -> dict[str, str]:
    """Every generated protobuf file of the platform: path -> text."""
    return {f.path: file_text(platform, f) for f in platform.files}
