# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Outputs of the Go binaries' environment (ADR-2350 D13).

- `<binary dir>/config_keys.gen.go`: the binary's golusoris CompoundKeys.
- The environment table of each binary, generated into its page and into
  docs/usage/env-vars.md, one uniform table: variable, key, type, default, the
  chart values that set it, description.
- deploy/helm/vmafx/templates/_config.gen.tpl: one helper per chart workload,
  `vmafx.env.<workload>`, holding every `VMAFX_*` entry of that workload in
  order with its comment and condition, and the value maps
  (`vmafx.backendEnvValue`). A template includes the helper where its
  environment list holds those entries; the entries carry the list's
  indentation, so the render is the one the hand-written lists gave.
"""

from __future__ import annotations

import posixpath
import re
from pathlib import Path

from .config import ChartEnv, Config, ConfigBinary, ConfigVar, chart_values, compound_keys
from .splice import splice, spliced

TEMPLATE = "deploy/helm/vmafx/templates/_config.gen.tpl"
ENV_PAGE = "docs/usage/env-vars.md"
GO_FILE = "config_keys.gen.go"
GO_HEADER = """// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.

package {package}

// compoundKeys are the configuration keys of vmafx-{binary} whose own name
// holds an underscore. golusoris turns every underscore of a VMAFX_ variable
// into the key delimiter except in these keys, so {example}
// reaches {key} (ADR-2350 D13; the [[config]] entries of
// api/vmafx-platform.toml).
var compoundKeys = []string{{
{items}}}
"""
COLUMNS = "| Variable | Key | Type | Default | Chart value | Description |"
RULE = "|---|---|---|---|---|---|"


# ---------------------------------------------------------------------------
# Go
# ---------------------------------------------------------------------------


def go_text(config: Config, binary: ConfigBinary) -> str:
    keys = compound_keys(config, binary.name)
    first = keys[0]
    items = "".join(f'\t"{key}",\n' for key in keys)
    example = "VMAFX_" + first.upper().replace(".", "_")
    return GO_HEADER.format(
        binary=binary.name, package=binary.package, example=example, key=first, items=items
    )


def go_files(config: Config) -> dict[str, str]:
    return {
        f"{b.dir}/{GO_FILE}": go_text(config, b)
        for b in config.binaries
        if compound_keys(config, b.name)
    }


# ---------------------------------------------------------------------------
# Documentation
# ---------------------------------------------------------------------------


def markers(binary: str) -> tuple[str, str]:
    region = f"vmafx-api environment vmafx-{binary}"
    return (
        f"<!-- BEGIN GENERATED: {region} (scripts/codegen/vmafx-api.py) -->",
        f"<!-- END GENERATED: {region} -->",
    )


DOCS_LINK = re.compile(r"\]\(/([^)#]+)(#[^)]*)?\)")


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _links(text: str, page: str) -> str:
    """Docs-root links (`](/server/auth.md#x)`) made relative to `page`."""
    base = posixpath.dirname(posixpath.relpath(page, "docs"))

    def relative(match: re.Match[str]) -> str:
        target = posixpath.relpath(match.group(1), base or ".")
        return f"]({target}{match.group(2) or ''})"

    return DOCS_LINK.sub(relative, text)


def _row(config: Config, var: ConfigVar, binary: ConfigBinary) -> str:
    values = chart_values(config, var.env, binary.workloads)
    chart = ", ".join(f"`{v}`" for v in values) if values else ""
    if not values and any(
        var.env == e.env for e in config.env if set(e.workloads) & set(binary.workloads)
    ):
        chart = "set by the chart"
    doc = var.field(binary.name, "doc")
    if var.secret:
        doc = f"Secret. {doc}"
    own = var.field(binary.name, "key")
    key = f"`{own}`" if own else "read directly"
    cells = [
        f"`{var.env}`",
        key,
        var.field(binary.name, "type"),
        var.field(binary.name, "default"),
        chart,
        doc,
    ]
    return "| " + " | ".join(_cell(c) for c in cells) + " |"


def table(config: Config, binary: ConfigBinary, page: str = ENV_PAGE) -> list[str]:
    rows = [
        _links(_row(config, v, binary), page) for v in config.variables if binary.name in v.binaries
    ]
    return ["", COLUMNS, RULE, *rows, ""]


def pages(config: Config, root: Path) -> dict[str, str]:
    """Each binary's page and docs/usage/env-vars.md with their tables generated."""
    out: dict[str, str] = {}
    for binary in config.binaries:
        begin, end = markers(binary.name)
        for path in (binary.page, ENV_PAGE):
            body = table(config, binary, path)
            if path in out:
                out[path] = splice(out[path], begin, end, body, path)
            else:
                out[path] = spliced(root, path, begin, end, body)
    return out


# ---------------------------------------------------------------------------
# Chart
# ---------------------------------------------------------------------------


def _entry_lines(entry: ChartEnv, pad: str) -> list[str]:
    lines = [pad + line for line in entry.comment.splitlines()]
    lines.append(f"{pad}- name: {entry.env}")
    if entry.value:
        lines.append(f"{pad}  value: {entry.value}")
    elif entry.field_ref:
        lines += [
            f"{pad}  valueFrom:",
            f"{pad}    fieldRef:",
            f"{pad}      fieldPath: {entry.field_ref}",
        ]
    else:
        name, key = entry.secret_ref or ("", "")
        lines += [
            f"{pad}  valueFrom:",
            f"{pad}    secretKeyRef:",
            f"{pad}      name: {name}",
            f"{pad}      key: {key}",
        ]
    if entry.when:
        return [f"{{{{- if {entry.when} }}}}", *lines, "{{- end }}"]
    return lines


def _workload_text(config: Config, name: str, indent: int, doc: str) -> list[str]:
    pad = " " * indent
    body: list[str] = []
    for entry in config.env:
        if name in entry.workloads:
            body += _entry_lines(entry, pad)
    return [
        "{{/*",
        f"vmafx.env.{name} — {doc}",
        "*/}}",
        f'{{{{- define "vmafx.env.{name}" }}}}',
        *body,
        "{{- end }}",
        "",
    ]


def _map_text(config: Config) -> list[str]:
    out: list[str] = []
    for chart_map in config.maps:
        out += ["{{/*", f"{chart_map.name} — {chart_map.doc}", "*/}}"]
        out.append(f'{{{{- define "{chart_map.name}" -}}}}')
        for i, (case, value) in enumerate(chart_map.cases):
            keyword = "if" if i == 0 else "else if"
            out += [f'{{{{- {keyword} eq {chart_map.source} "{case}" -}}}}', value]
        out += ["{{- else -}}", chart_map.default, "{{- end }}", "{{- end }}", ""]
    return out


def template_text(config: Config) -> str:
    head = [
        "{{- /*",
        "  " + "SPDX-" + "License-Identifier: EUPL-1.2",  # split: not this file's header
        "  Copyright 2026 Lusoris",
        "",
        "  Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.",
        "",
        "  The VMAFX_* environment entries of every workload of the chart (ADR-2350",
        "  D13): the [[chart_env]] entries of the definition, in order, with their",
        "  comments and conditions; the value maps of [[chart_maps]].",
        "*/}}",
        "",
    ]
    body = _map_text(config)
    for workload in config.workloads:
        body += _workload_text(config, workload.name, workload.indent, workload.doc)
    return "\n".join(head + body).rstrip("\n") + "\n"


def files(config: Config) -> dict[str, str]:
    out = go_files(config)
    out[TEMPLATE] = template_text(config)
    return out
