# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Go types of the platform's Kubernetes resources (ADR-2350 D13).

Per `[[groups]]` entry: `groupversion_info.go` (group, version, scheme
builder). Per `[[resources]]` entry: `<kind lower-cased>_types.go` with the
enums and messages its spec and status reach (each type in the file of the
first resource that reaches it), the root type with its kubebuilder markers,
its list type and the scheme registration. controller-gen then writes the
deepcopy code, the CRDs and the RBAC roles (scripts/codegen/crd_generate.py).
The output is gofmt-clean: fields are separated by blank lines, and the two
aligned groups of a root type are padded as gofmt pads them.
"""

from __future__ import annotations

import textwrap
from typing import Any

from .kube import SCALARS, Group, Kube, KubeEnum, KubeField, KubeMessage, Resource

WIDTH = 80
HEADER = """// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.
//
// {what} (ADR-2350 D13). Change the definition and run
// `python3 scripts/codegen/vmafx-api.py --write`, then
// `python3 scripts/codegen/crd_generate.py --write` (deepcopy, CRDs, RBAC).

"""
RESOURCE_COPY = """// deepCopier is a spec or status type of this group; controller-gen writes its
// DeepCopyInto.
type deepCopier[T any] interface {
	*T
	DeepCopyInto(out *T)
}

// deepCopyResource copies one custom resource into another: its type and
// object metadata, its spec and its status. Every resource's DeepCopyInto
// calls it, so the copy of a resource is written once (HISS-19).
func deepCopyResource[Spec, Status any, InSpec deepCopier[Spec], InStatus deepCopier[Status]](
	inType metav1.TypeMeta, inMeta *metav1.ObjectMeta, inSpec InSpec, inStatus InStatus,
	outType *metav1.TypeMeta, outMeta *metav1.ObjectMeta, outSpec *Spec, outStatus *Status,
) {
	*outType = inType
	inMeta.DeepCopyInto(outMeta)
	inSpec.DeepCopyInto(outSpec)
	inStatus.DeepCopyInto(outStatus)
}
"""
MARKERS = {
    "enum": "+kubebuilder:validation:Enum={}",
    "items_enum": "+kubebuilder:validation:items:Enum={}",
    "minimum": "+kubebuilder:validation:Minimum={}",
    "min_length": "+kubebuilder:validation:MinLength={}",
    "items_min_length": "+kubebuilder:validation:items:MinLength={}",
    "max_items": "+kubebuilder:validation:MaxItems={}",
    "pattern": "+kubebuilder:validation:Pattern=`{}`",
    "format": "+kubebuilder:validation:Format={}",
}


def comment(text: str, indent: str = "") -> list[str]:
    width = WIDTH - len(indent) - 3
    return [f"{indent}// {line}" for line in textwrap.wrap(text, width=width)]


def _scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return f'"{value}"'
    return str(value)


def _value(value: Any) -> str:
    """A default in marker syntax; a list holds scalars only (kube.py checks)."""
    if isinstance(value, list):
        return "{" + ",".join(_scalar(v) for v in value) + "}"
    return _scalar(value)


def _marker(key: str, value: Any) -> str:
    rendered = ";".join(str(v) for v in value) if isinstance(value, list) else str(value)
    return MARKERS[key].format(rendered)


def go_type(kube: Kube, fld: KubeField) -> str:
    base = SCALARS.get(fld.type, fld.type)
    if fld.repeated:
        return "[]" + base
    return ("*" + base) if fld.pointer else base


def _field(kube: Kube, fld: KubeField) -> list[str]:
    lines = comment(fld.doc, "\t")
    lines += [f"\t// {_marker(k, v)}" for k, v in fld.validation]
    if fld.default is not None:
        lines.append(f"\t// +kubebuilder:default:={_value(fld.default)}")
    lines.append("\t// +optional" if fld.optional else "\t// +required")
    tag = fld.name + (",omitempty" if fld.optional else "")
    return [*lines, f'\t{fld.go} {go_type(kube, fld)} `json:"{tag}"`']


def _message(kube: Kube, message: KubeMessage) -> list[str]:
    lines = [*comment(message.doc), f"type {message.name} struct {{"]
    for i, fld in enumerate(message.fields):
        lines += ([""] if i else []) + _field(kube, fld)
    return [*lines, "}"]


def _enum(enum: KubeEnum) -> list[str]:
    values = ";".join(v.name for v in enum.values)
    lines = [
        *comment(enum.doc),
        "//",
        f"// +kubebuilder:validation:Enum={values}",
        f"type {enum.name} string",
        "",
        "const (",
    ]
    for i, value in enumerate(enum.values):
        const = enum.name + value.name
        doc = f"{const}: {value.doc}" if value.doc else f"{const} is {value.name}."
        lines += ([""] if i else []) + comment(doc, "\t")
        lines.append(f'\t{const} {enum.name} = "{value.name}"')
    return [*lines, ")"]


def align(rows: list[list[str]]) -> list[str]:
    """Tab-align struct lines as gofmt does: every cell but a line's last is
    padded to the widest cell of its column among consecutive lines that have
    a cell after it."""
    widths: list[list[int]] = [[0] * len(r) for r in rows]
    columns = max(len(r) for r in rows)
    for col in range(columns - 1):
        block: list[int] = []
        for i, row in enumerate([*rows, []]):
            if len(row) > col + 1:
                block.append(i)
                continue
            width = max((len(rows[j][col]) for j in block), default=0)
            for j in block:
                widths[j][col] = width
            block = []
    out = []
    for row, w in zip(rows, widths, strict=True):
        cells = [cell.ljust(w[c]) if c < len(row) - 1 else cell for c, cell in enumerate(row)]
        out.append("\t" + " ".join(cells))
    return out


def _root(resource: Resource) -> list[str]:
    columns = [
        f'// +kubebuilder:printcolumn:name="{c.name}",type="{c.type}",JSONPath="{c.json_path}"'
        for c in resource.printer_columns
    ]
    short = ";".join(resource.short_names)
    scope = f"scope={resource.scope}" + (f",shortName={short}" if short else "")
    spec_tag = '`json:"spec"`' if resource.spec_required else '`json:"spec,omitempty"`'
    meta = align(
        [
            ["metav1.TypeMeta", '`json:",inline"`'],
            ["metav1.ObjectMeta", '`json:"metadata,omitempty"`'],
        ]
    )
    body = align(
        [
            ["Spec", resource.spec, spec_tag],
            ["Status", resource.status, '`json:"status,omitempty"`'],
        ]
    )
    markers = ["// +kubebuilder:object:root=true"]
    markers += ["// +kubebuilder:subresource:status"] if resource.status_subresource else []
    markers += [f"// +kubebuilder:resource:{scope}", *columns]
    return [
        *comment(resource.doc),
        "//",
        *markers,
        f"type {resource.kind} struct {{",
        *meta,
        "",
        *body,
        "}",
    ]


def _copy(resource: Resource) -> list[str]:
    """The root type's DeepCopyInto: one call of deepCopyResource
    (groupversion_info.go). controller-gen finds it and writes only DeepCopy
    and DeepCopyObject for the root type."""
    kind = resource.kind
    return [
        *comment(
            f"DeepCopyInto copies the receiver into out through deepCopyResource; "
            f"controller-gen writes DeepCopy and DeepCopyObject of {kind} around it."
        ),
        f"func (in *{kind}) DeepCopyInto(out *{kind}) {{",
        "\tdeepCopyResource(in.TypeMeta, &in.ObjectMeta, &in.Spec, &in.Status,",
        "\t\t&out.TypeMeta, &out.ObjectMeta, &out.Spec, &out.Status)",
        "}",
    ]


def _list(resource: Resource) -> list[str]:
    rows = [
        ["metav1.TypeMeta", '`json:",inline"`'],
        ["metav1.ListMeta", '`json:"metadata,omitempty"`'],
        ["Items", f"[]{resource.kind}", '`json:"items"`'],
    ]
    return [
        f"// {resource.kind}List contains a list of {resource.kind}.",
        "//",
        "// +kubebuilder:object:root=true",
        f"type {resource.kind}List struct {{",
        *align(rows),
        "}",
    ]


def _reached(kube: Kube, resource: Resource) -> list[str]:
    """The enum and message names the resource's spec and status reach, in
    the order they are first met. A name is queued once and never a scalar, so
    every pass appends one new type: the loop runs at most once per type."""
    messages = {m.name: m for m in kube.messages}
    order: list[str] = []
    pending = [resource.spec, resource.status]
    for _ in range(len(messages) + len(kube.enums)):
        if not pending:
            break
        name = pending.pop(0)
        order.append(name)
        for fld in messages[name].fields if name in messages else ():
            if fld.type not in SCALARS and fld.type not in order and fld.type not in pending:
                pending.append(fld.type)
    return order


def resource_text(kube: Kube, resource: Resource, owned: list[str]) -> str:
    group = kube.group(resource.group)
    package = group.path.rsplit("/", 1)[-1]
    head = HEADER.format(what=f"Go types of the {resource.kind} custom resource")
    head += f"package {package}\n\n"
    imports = ['metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"']
    head += "import (\n" + "".join(f"\t{i}\n" for i in imports) + ")\n\n"
    blocks = [_enum(e) for name in owned for e in kube.enums if e.name == name]
    blocks += [_message(kube, m) for name in owned for m in kube.messages if m.name == name]
    blocks += [_root(resource), _copy(resource), _list(resource)]
    blocks.append(
        [
            "func init() {",
            f"\tSchemeBuilder.Register(&{resource.kind}{{}}, &{resource.kind}List{{}})",
            "}",
        ]
    )
    return head + "\n\n".join("\n".join(b) for b in blocks) + "\n"


def group_text(group: Group) -> str:
    package = group.path.rsplit("/", 1)[-1]
    head = HEADER.format(what=f"The {group.group}/{group.version} API group")
    return (
        head
        + "\n".join(comment(group.doc))
        + f"\n//\n// +kubebuilder:object:generate=true\n// +groupName={group.group}\npackage {package}\n\n"
        + "import (\n"
        + '\tmetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"\n'
        + '\t"k8s.io/apimachinery/pkg/runtime/schema"\n'
        + '\t"sigs.k8s.io/controller-runtime/pkg/scheme"\n'
        + ")\n\n"
        + "var (\n"
        + "\t// GroupVersion is the group/version for this API.\n"
        + f'\tGroupVersion = schema.GroupVersion{{Group: "{group.group}", Version: "{group.version}"}}\n\n'
        + "\t// SchemeBuilder is used to add Go types to the GroupVersionKind scheme.\n"
        + "\tSchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}\n\n"
        + "\t// AddToScheme adds the types in this group-version to the given scheme.\n"
        + "\tAddToScheme = SchemeBuilder.AddToScheme\n"
        + ")\n\n"
        + RESOURCE_COPY
    )


def files(kube: Kube) -> dict[str, str]:
    """Every generated Go file of the Kubernetes types: path -> text."""
    out = {f"{g.path}/groupversion_info.go": group_text(g) for g in kube.groups}
    seen: set[str] = set()
    for resource in kube.resources:
        owned = [n for n in _reached(kube, resource) if n not in seen]
        seen.update(owned)
        path = f"{kube.group(resource.group).path}/{resource.kind.lower()}_types.go"
        out[path] = resource_text(kube, resource, owned)
    return out
