// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.

package main

// compoundKeys are the configuration keys of vmafx-server whose own name
// holds an underscore. golusoris turns every underscore of a VMAFX_ variable
// into the key delimiter except in these keys, so VMAFX_GRPC_CERT_FILE
// reaches grpc.cert_file (ADR-2350 D13; the [[config]] entries of
// api/vmafx-platform.toml).
var compoundKeys = []string{
	"grpc.cert_file",
	"grpc.key_file",
	"grpc.max_recv_size",
	"grpc.max_send_size",
}
