#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Render docs/hardware-reports/index.md and the table of docs/usage/hardware-we-need.md.

Both come from the report files in docs/hardware-reports/; the table of the page also
reads scripts/docs/hardware-needs.json (the families wanted) and the row maps of
tools/rc1-tester/image/.

Flags:
    --check   Exit 1 when an in-tree output differs from the rendering, when a GPU family
              of a row map has no row in hardware-needs.json, or when a state id is not in
              docs/state.md.
    --write   Rewrite the outputs.

Wired into `make docs-fragments-check` / `make docs-fragments-write` (ADR-0221 pattern).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "rc1-tester" / "src"))

from vmaf_rc1_tester.hw_report import CHECK_KEYS, PASSING  # noqa: E402

DIRECTORY = ROOT / "docs" / "hardware-reports"
OUTPUT = DIRECTORY / "index.md"
SCHEMA_NAME = "report.schema.json"
NEEDS = ROOT / "scripts" / "docs" / "hardware-needs.json"
NEEDS_PAGE = ROOT / "docs" / "usage" / "hardware-we-need.md"
IMAGE_DIR = ROOT / "tools" / "rc1-tester" / "image"
STATE = ROOT / "docs" / "state.md"
BEGIN = "<!-- hardware-needs:begin (generated by scripts/docs/generate-hardware-reports.py) -->"
END = "<!-- hardware-needs:end -->"
PACKAGES = {
    "macos": ("macOS bundle", "a-native-macos-bundle-apple-silicon"),
    "container": ("container image", "b-container-image"),
    "sycl": ("Intel GPU image", "c-intel-gpu-image-linux-or-windows-with-wsl2"),
    "cuda": ("NVIDIA GPU image", "d-nvidia-gpu-image-linux-or-windows-with-wsl2"),
    "hip": ("AMD GPU image", "e-amd-gpu-image-linux"),
    "windows": ("Windows zip", "f-native-windows-zip-x64-or-arm64"),
    "windows-cuda": ("Windows CUDA zip", "with-an-nvidia-gpu-the-cuda-zip"),
    "windows-sycl": ("Windows SYCL zip", "with-an-intel-gpu-the-sycl-zip"),
}
GPU_BACKENDS = ("cuda", "hip", "sycl")
# The checks of a report that are about the processor (hw_report.CHECK_KEYS names). A CPU
# row takes their verdict, not the report's: a GPU section's failure is a finding about the
# GPU. The native macOS row also closes the Metal rows, so its own checks add Metal's.
CPU_CHECKS = ("dispatch", "reference", "unit", "golden")
METAL_CHECKS = ("metal", "gate")

HEADER = """\
<!-- GENERATED by scripts/docs/generate-hardware-reports.py from the report
files in this directory; do not edit by hand. Add a report file and run
`make docs-fragments-write`. -->

# Hardware reports

Reports printed by the [tester image](../usage/tester-image.md) on machines outside
the project's own hosts, one file per report. Each row links the file. The
[report schema](report.schema.json) lists every field, and the CI gate
`scripts/ci/check-hardware-reports.py` validates each file. A report with
verdict `fail` is welcome: it is a finding.

"""
TABLE = """\
| Date | CPU | Arch | Dispatch flags | GPU | Verdict | Source commit | Report |
| --- | --- | --- | --- | --- | --- | --- | --- |
"""
EMPTY = "No reports have been submitted yet.\n"


def _gpus(report: dict[str, Any]) -> str:
    """The GPUs a schema-3 report measured, with their family; `-` for none."""
    gpu = report.get("gpu") or {}
    names = [
        f"{d['facts'].get('name', '?')} ({d['facts'].get('family', '?')})"
        for d in gpu.get("devices", [])
    ]
    return ", ".join(names).replace("|", "/") or "-"


def _row(path: Path) -> str:
    report = json.loads(path.read_text(encoding="utf-8"))
    host = report["host"]
    cells = [
        report["generated_utc"][:10],
        host["cpu_model"].replace("|", "/"),
        host["machine"],
        ", ".join(host["dispatch_flags"]) or "none",
        _gpus(report),
        report["verdict"],
        f"`{report['image']['source_commit'][:12]}`",
        f"[{path.name}]({path.name})",
    ]
    return "| " + " | ".join(cells) + " |"


def render(directory: Path) -> str:
    paths = [p for p in sorted(directory.glob("*.json")) if p.name != SCHEMA_NAME]
    if not paths:
        return HEADER + EMPTY
    return HEADER + TABLE + "\n".join(_row(p) for p in paths) + "\n"


def _host_matches(match: dict[str, Any], report: dict[str, Any]) -> bool:
    """Whether a report's host satisfies the CPU part of a row's `match`."""
    host = report["host"]
    flags = set(host["dispatch_flags"])
    return (
        ("platform" not in match or host["platform"] == match["platform"])
        and ("machine" not in match or host["machine"] in match["machine"])
        and set(match.get("flags_all", [])) <= flags
        and not set(match.get("flags_none", [])) & flags
        and (
            "cpu_model_re" not in match or bool(re.search(match["cpu_model_re"], host["cpu_model"]))
        )
    )


def _gpu_verdicts(match: dict[str, Any], report: dict[str, Any]) -> list[str]:
    """One verdict per device of the report that belongs to the row's GPU families (and,
    when the row names one, ran on its platform)."""
    gpu = report.get("gpu") or {}
    if gpu.get("backend") != match["gpu_backend"]:
        return []
    if "platform" in match and report["host"]["platform"] != match["platform"]:
        return []
    found = []
    for device in gpu.get("devices", []):
        if device["facts"].get("family") in match["gpu_families"]:
            rows = device["rows"]["status"]
            found.append("fail" if "fail" in (device["status"], rows) else rows)
    return found


def _host_verdict(row: dict[str, Any], report: dict[str, Any]) -> str:
    """`fail` when one of the row's own checks failed (or the image's files do not match
    its build), else `pass`. A section an older schema lacks is not counted."""
    checks = CPU_CHECKS + (METAL_CHECKS if row.get("metal_rows") else ())
    keys = [CHECK_KEYS[check] for check in checks]
    failed = [k for k in keys if k in report and report[k]["status"] not in PASSING[k]]
    if failed or not report["image"]["files_match_build"]:
        return "fail"
    return "pass"


def _verdicts(row: dict[str, Any], reports: list[dict[str, Any]]) -> list[str]:
    """The verdict of every report (every device, for a GPU row) that counts for a row."""
    match = row["match"]
    found: list[str] = []
    for report in reports:
        if "gpu_backend" in match:
            found += _gpu_verdicts(match, report)
        elif _host_matches(match, report):
            found.append(_host_verdict(row, report))
    return found


def _status(row: dict[str, Any], reports: list[dict[str, Any]]) -> str:
    verdicts = _verdicts(row, reports)
    owner = f"covered by {row['owner']}" if row["owner"] else ""
    if not verdicts:
        return owner or "no report yet"
    worst = (
        "fail" if "fail" in verdicts else ("pass" if "pass" in verdicts else "not fully measured")
    )
    reported = f"{len(verdicts)} reported, worst {worst}"
    return f"{owner}; {reported}" if owner else reported


def _state_cell(row: dict[str, Any], metal_count: int) -> str:
    cells = [f"[`{i}`](../state.md)" for i in row["state"]]
    if row.get("metal_rows"):
        cells.append(
            f"the {metal_count} open Metal rows ([list](tester-image.md#metal-state-rows))"
        )
    return ", ".join(cells)


def render_needs_table(needs: dict[str, Any], reports: list[dict[str, Any]]) -> str:
    metal = json.loads((IMAGE_DIR / "metal-rows.json").read_text(encoding="utf-8"))
    head = (
        "| Hardware family | Run this package | Closes (state row) | Status |\n"
        "| --- | --- | --- | --- |\n"
    )
    lines = []
    for row in needs["rows"]:
        name, anchor = PACKAGES[row["package"]]
        cells = [
            row["family"],
            f"[{name}](tester-image.md#{anchor})",
            _state_cell(row, len(metal["rows"])),
            _status(row, reports),
        ]
        lines.append("| " + " | ".join(c.replace("|", "/") for c in cells) + " |")
    return head + "\n".join(lines) + "\n"


def needs_problems(needs: dict[str, Any]) -> list[str]:
    """Rows that disagree with the row maps or the state ledger."""
    problems = []
    for backend in GPU_BACKENDS:
        wanted = json.loads((IMAGE_DIR / f"{backend}-rows.json").read_text(encoding="utf-8"))
        mapped = {f for row in wanted["rows"] for f in row.get("families", [])}
        # A row bound to one platform (a Windows GPU zip's) covers no family: every
        # family still needs its own row.
        listed = {
            f
            for row in needs["rows"]
            if row["match"].get("gpu_backend") == backend and "platform" not in row["match"]
            for f in row["match"]["gpu_families"]
        }
        problems += [
            f"{backend} family {f} has no row in {NEEDS.name}" for f in sorted(mapped - listed)
        ]
        problems += [
            f"{backend} family {f} of {NEEDS.name} is in no row map"
            for f in sorted(listed - mapped)
        ]
    state = STATE.read_text(encoding="utf-8")
    ids = {i for row in needs["rows"] for i in row["state"]}
    problems += [
        f"state id {i} is not in docs/state.md" for i in sorted(ids) if f"**{i}**" not in state
    ]
    problems += [
        f"unknown package {r['package']}" for r in needs["rows"] if r["package"] not in PACKAGES
    ]
    return problems


def splice(page: str, table: str) -> str:
    """The page with the text between the two markers replaced by the table."""
    head, sep, rest = page.partition(BEGIN)
    if not sep or END not in rest:
        raise ValueError(f"{NEEDS_PAGE.name} lacks the {BEGIN!r} / {END!r} markers")
    tail = rest.partition(END)[2]
    return f"{head}{BEGIN}\n\n{table}\n{END}{tail}"


def load_reports(directory: Path) -> list[dict[str, Any]]:
    paths = [p for p in sorted(directory.glob("*.json")) if p.name != SCHEMA_NAME]
    return [json.loads(p.read_text(encoding="utf-8")) for p in paths]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    needs = json.loads(NEEDS.read_text(encoding="utf-8"))
    problems = needs_problems(needs)
    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        return 1
    outputs = {
        OUTPUT: render(DIRECTORY),
        NEEDS_PAGE: splice(
            NEEDS_PAGE.read_text(encoding="utf-8"),
            render_needs_table(needs, load_reports(DIRECTORY)),
        ),
    }
    stale = [
        p for p, text in outputs.items() if not p.is_file() or p.read_text(encoding="utf-8") != text
    ]
    if args.write:
        for path in stale:
            path.write_text(outputs[path], encoding="utf-8")
        return 0
    for path in stale:
        print(
            f"{path.relative_to(ROOT)} is stale; run `make docs-fragments-write`", file=sys.stderr
        )
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
