#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Render docs/hardware-reports/index.md from the report files next to it.

Flags:
    --check   Exit 1 when the in-tree index differs from the rendering.
    --write   Rewrite the index.

Wired into `make docs-fragments-check` / `make docs-fragments-write` (ADR-0221 pattern).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DIRECTORY = ROOT / "docs" / "hardware-reports"
OUTPUT = DIRECTORY / "index.md"
SCHEMA_NAME = "report.schema.json"

HEADER = """\
<!-- GENERATED by scripts/docs/generate-hardware-reports.py from the report
files in this directory; do not edit by hand. Add a report file and run
`make docs-fragments-write`. -->

# Hardware reports

Reports printed by the [tester image](../usage/tester-image.md) on machines outside
the project's own hosts, one file per report. Each row links the file. The
[report schema](report.schema.json) lists every field, and the CI gate
`scripts/ci/check-hardware-reports.py` validates each file. A report with
verdict `fail` is welcome: it is a finding.

"""
TABLE = """\
| Date | CPU | Arch | Dispatch flags | Verdict | Source commit | Report |
| --- | --- | --- | --- | --- | --- | --- |
"""
EMPTY = "No reports have been submitted yet.\n"


def _row(path: Path) -> str:
    report = json.loads(path.read_text(encoding="utf-8"))
    host = report["host"]
    cells = [
        report["generated_utc"][:10],
        host["cpu_model"].replace("|", "/"),
        host["machine"],
        ", ".join(host["dispatch_flags"]) or "none",
        report["verdict"],
        f"`{report['image']['source_commit'][:12]}`",
        f"[{path.name}]({path.name})",
    ]
    return "| " + " | ".join(cells) + " |"


def render(directory: Path) -> str:
    paths = [p for p in sorted(directory.glob("*.json")) if p.name != SCHEMA_NAME]
    if not paths:
        return HEADER + EMPTY
    return HEADER + TABLE + "\n".join(_row(p) for p in paths) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    text = render(DIRECTORY)
    if args.write:
        OUTPUT.write_text(text, encoding="utf-8")
        return 0
    if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
        print(
            f"{OUTPUT.relative_to(ROOT)} is stale; run `make docs-fragments-write`", file=sys.stderr
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
