#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Render the allowlist of the upstream parity guard from ``scripts/ci/upstream_parity.d/``.

Inputs: one fragment per allowed difference under ``scripts/ci/upstream_parity.d/``
(loaded and validated by ``scripts/ci/upstream_parity_allowlist.py``).
Output: ``docs/development/upstream-parity-allowlist.md``.

Flags:
    --check   Exit 1 when the in-tree output differs from the rendering.
    --write   Rewrite the output file.

Wired into ``make docs-fragments-check`` / ``make docs-fragments-write``
(ADR-0221 pattern, ADR-1487).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from scripts.ci.upstream_parity_allowlist import (  # noqa: E402
    ADR_DIR,
    FRAGMENTS_DIR,
    AllowlistError,
    Fragment,
    load_fragments,
)

OUTPUT = ROOT / "docs" / "development" / "upstream-parity-allowlist.md"

HEADER = """\
<!-- GENERATED by scripts/docs/generate-upstream-parity-allowlist.py from
scripts/ci/upstream_parity.d/; do not edit by hand. Add or remove a fragment
file and run `make docs-fragments-write`. -->
<!-- markdownlint-disable MD013 MD060 -->

# Allowed differences from Netflix/vmaf

Every row is one fragment of the upstream parity guard's allowlist: a place
where this tree's CPU result differs from Netflix/vmaf at the recorded parity
head, why, and by how much at most. Anything the guard finds that no row
covers fails it, and so does a row nothing matches any more. The guard, the
fragment keys and the way a row is added or removed are in the
[upstream parity guide](upstream-parity.md).

"""

DELIBERATE = """\
## Deliberate deviations

| Fragment | Kind | Scope | Metrics | Bound | ADR | Upstream | Evidence |
| --- | --- | --- | --- | --- | --- | --- | --- |
"""

PENDING = """\

## Pending: differences that are to disappear

A pending row names the branch whose landing ends the difference. The row
then matches nothing, the guard fails as stale, and the fragment is removed.

| Fragment | Kind | Scope | Metrics | Bound | Branch | ADR | Evidence |
| --- | --- | --- | --- | --- | --- | --- | --- |
"""


PENDING_NONE = """\

## Pending: differences that are to disappear

None: every fragment above is a deliberate deviation with an ADR.
"""


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def _code_list(items: tuple[str, ...]) -> str:
    return ", ".join(f"`{_cell(item)}`" for item in items)


def _adr_links(fragment: Fragment, adr_dir: Path) -> str:
    links = []
    for adr in fragment.adrs:
        target = sorted(adr_dir.glob(f"{adr[4:]}-*.md"))[0].name
        links.append(f"[{adr}](../adr/{target})")
    return ", ".join(links) or "none"


def _upstream_links(fragment: Fragment) -> str:
    links = []
    for reference in fragment.upstream:
        number = reference.rsplit("#", 1)[1]
        links.append(f"[{reference}](https://github.com/Netflix/vmaf/issues/{number})")
    return ", ".join(links) or "none yet"


def _scope(fragment: Fragment) -> str:
    parts = [f"runs {_code_list(fragment.runs)}"]
    if fragment.fixtures != ("*",):
        parts.append(f"fixtures {_code_list(fragment.fixtures)}")
    if fragment.frames != ("*",):
        parts.append(f"at {_code_list(fragment.frames)}")
    if fragment.dispatch:
        parts.append(f"dispatch {_code_list(fragment.dispatch)}")
    return "; ".join(parts)


def _bound(fragment: Fragment) -> str:
    parts = []
    if fragment.bound is not None:
        parts.append(f"{fragment.bound:g}")
    if fragment.status:
        parts.append("ends " + ", ".join(f"{up} / {fork}" for up, fork in fragment.status))
    if fragment.side:
        parts.append(f"only {fragment.side} emits")
    return "; ".join(parts)


def _row(fragment: Fragment, adr_dir: Path) -> str:
    cells = [
        f"`{fragment.name}`",
        fragment.kind,
        _scope(fragment),
        _code_list(fragment.metrics) or "all",
        _bound(fragment),
    ]
    if fragment.pending:
        cells += [f"`{fragment.branch}`", _adr_links(fragment, adr_dir)]
    else:
        cells += [_adr_links(fragment, adr_dir), _upstream_links(fragment)]
    cells.append(_cell(fragment.evidence))
    return "| " + " | ".join(cells) + " |\n"


def render(fragments_dir: Path = FRAGMENTS_DIR, adr_dir: Path = ADR_DIR) -> str:
    """Return the full text of the generated page."""

    fragments = load_fragments(fragments_dir, adr_dir)
    deliberate = [fragment for fragment in fragments if not fragment.pending]
    pending = [fragment for fragment in fragments if fragment.pending]
    text = HEADER + DELIBERATE + "".join(_row(fragment, adr_dir) for fragment in deliberate)
    if pending:
        text += PENDING + "".join(_row(fragment, adr_dir) for fragment in pending)
    else:
        # Keep the section and its anchor when nothing is pending: the
        # ledger and the guide link to it.
        text += PENDING_NONE
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--fragments", type=Path, default=FRAGMENTS_DIR)
    parser.add_argument("--adr-dir", type=Path, default=ADR_DIR)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)
    try:
        text = render(args.fragments, args.adr_dir)
    except AllowlistError as exc:
        print(f"upstream parity allowlist: {exc}", file=sys.stderr)
        return 65
    if args.write:
        args.output.write_text(text, encoding="utf-8")
        return 0
    current = args.output.read_text(encoding="utf-8") if args.output.is_file() else None
    if current != text:
        print(f"{args.output} is stale; run `make docs-fragments-write`", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
