#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Write the title lists that keep record titles in the site search (ADR-1512).

The site search leaves the bodies of ADRs and research digests out of its
index (``docs/adr/.meta.yml``, ``docs/research/.meta.yml``). A long index page
ranks low for a title query, so this script writes one page per record kind
with every record's title as its own heading: each heading is a search entry,
and its link leads to the record.

Outputs:
    docs/adr/titles.md        one heading per ADR (docs/adr/NNNN-*.md)
    docs/research/titles.md   one heading per research digest

Each page has ``search: exclude: false`` front matter, so it stays in the index
while its directory's ``.meta.yml`` keeps the records out, and hides its table
of contents.

Flags:
    --check   exit 1 when a list differs from the records.
    --write   rewrite both lists.

Wired into ``make docs-fragments-check`` / ``make docs-fragments-write``.
"""

from __future__ import annotations

import argparse
import html
import itertools
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NOT_RECORDS = {"README.md", "AGENTS.md", "titles.md", "0000-template.md"}
HEADING = re.compile(r"^#\s+(.+?)\s*$")


class TitleError(Exception):
    """A record has no title line."""


def title_of(path: Path) -> str:
    with path.open(encoding="utf-8") as handle:
        for line in itertools.islice(handle, 80):
            match = HEADING.match(line)
            if match:
                return match.group(1)
    raise TitleError(f"{path}: no '# ' title in its first 80 lines")


def render(text: str) -> str:
    """Escape a title for a Markdown heading, keeping authored code spans."""
    parts = re.split(r"(`+.*?`+)", text)
    for index in range(0, len(parts), 2):
        parts[index] = re.sub(r"(?<!\\)_", r"\\_", html.escape(parts[index], quote=False))
    return "".join(parts)


def records(directory: Path, pattern: str) -> list[Path]:
    return sorted(p for p in directory.glob(pattern) if p.is_file() and p.name not in NOT_RECORDS)


def page(heading: str, intro: str, entries: list[Path]) -> str:
    lines = [
        "---",
        "# Generated by scripts/docs/generate-record-titles.py; do not edit (ADR-1512).",
        f"title: {heading}",
        "search:",
        "  exclude: false",
        "hide:",
        "  - toc",
        "---",
        "",
        "<!-- markdownlint-disable MD013 MD024 MD025 MD038 -->",
        f"# {heading}",
        "",
        intro,
        "",
    ]
    for path in entries:
        lines += [f"## {render(title_of(path))}", "", f"[{path.stem}]({path.name})", ""]
    return "\n".join(lines)


def outputs(root: Path) -> dict[Path, str]:
    docs = root / "docs"
    adr = records(docs / "adr", "[0-9][0-9][0-9][0-9]-*.md")
    research = records(docs / "research", "*.md")
    return {
        docs
        / "adr"
        / "titles.md": page(
            "ADR titles",
            f"Every ADR, one heading each ({len(adr)}), so the site search finds an ADR by "
            "its title; ADR bodies are not in the search index "
            "([ADR-1512](1512-docs-search-user-pages-only.md)).",
            adr,
        ),
        docs
        / "research"
        / "titles.md": page(
            "Research digest titles",
            f"Every research digest, one heading each ({len(research)}), so the site search "
            "finds a digest by its title; digest bodies are not in the search index "
            "([ADR-1512](../adr/1512-docs-search-user-pages-only.md)).",
            research,
        ),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args(argv)
    try:
        expected = outputs(args.root)
    except (OSError, TitleError) as err:
        print(f"generate-record-titles: {err}", file=sys.stderr)
        return 1
    stale = []
    for path, text in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == text:
            continue
        if args.write:
            path.write_text(text, encoding="utf-8")
        else:
            stale.append(path)
    for path in stale:
        print(
            f"generate-record-titles: {path.relative_to(args.root)} is stale; run `make docs-fragments-write`",
            file=sys.stderr,
        )
    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main())
