#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Render the table of exact GPU twins from ``scripts/ci/exact_twins.d/``.

Inputs: one fragment per (feature, backend) under ``scripts/ci/exact_twins.d/``
(loaded and validated by ``scripts/ci/cross_backend_calibration.py``).
Output: ``docs/development/cross-backend-exact-twins.md``.

Flags:
    --check   Exit 1 when the in-tree output differs from the rendering.
    --write   Rewrite the output file.

Wired into ``make docs-fragments-check`` / ``make docs-fragments-write``
(ADR-0221 pattern, ADR-1428).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from scripts.ci.cross_backend_calibration import (  # noqa: E402
    ADR_DIR,
    EXACT_TWINS_DIR,
    ExactTwin,
    ExactTwinError,
    load_exact_twin_fragments,
)

OUTPUT = ROOT / "docs" / "development" / "cross-backend-exact-twins.md"

HEADER = """\
<!-- GENERATED by scripts/docs/generate-exact-twins.py from
scripts/ci/exact_twins.d/; do not edit by hand. Add or remove a fragment file
and run `make docs-fragments-write`. -->

# Exact GPU twins

Every row is a (feature, backend) pair whose scores equal the CPU extractor's
bits. A parity-gate cell whose two sides are `cpu` or listed twins of the
feature is compared with tolerance 0 at `--precision max`. The rule for
listing a twin is in the [cross-backend gate guide](cross-backend-gate.md#exact-twins).

| Feature | Backend | ADR | Evidence |
| --- | --- | --- | --- |
"""


def _adr_link(adr: str, adr_dir: Path) -> str:
    number = adr[4:]
    target = sorted(adr_dir.glob(f"{number}-*.md"))[0].name
    return f"[{adr}](../adr/{target})"


def _row(twin: ExactTwin, adr_dir: Path) -> str:
    adrs = ", ".join(_adr_link(adr, adr_dir) for adr in twin.adrs)
    evidence = twin.evidence.replace("|", "\\|")
    return f"| `{twin.feature}` | `{twin.backend}` | {adrs} | {evidence} |\n"


def render(fragments_dir: Path = EXACT_TWINS_DIR, adr_dir: Path = ADR_DIR) -> str:
    """Return the full text of the generated page."""

    twins = load_exact_twin_fragments(fragments_dir, adr_dir)
    return HEADER + "".join(_row(twin, adr_dir) for twin in twins)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument("--fragments", type=Path, default=EXACT_TWINS_DIR)
    parser.add_argument("--adr-dir", type=Path, default=ADR_DIR)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args(argv)
    try:
        text = render(args.fragments, args.adr_dir)
    except ExactTwinError as exc:
        print(f"exact twins: {exc}", file=sys.stderr)
        return 65
    if args.write:
        args.output.write_text(text, encoding="utf-8")
        return 0
    current = args.output.read_text(encoding="utf-8") if args.output.is_file() else None
    if current != text:
        print(
            f"{args.output} is stale; run `make docs-fragments-write`",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
