{{- /*
  SPDX-License-Identifier: EUPL-1.2
  Copyright 2026 Lusoris

  Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.

  The VMAFX_* environment entries of every workload of the chart (ADR-2350
  D13): the [[chart_env]] entries of the definition, in order, with their
  comments and conditions; the value maps of [[chart_maps]].
*/}}

{{/*
vmafx.backendEnvValue — the VMAFX_BACKEND value of the GPU vendor (gpu.vendor): the backend a node runs.
*/}}
{{- define "vmafx.backendEnvValue" -}}
{{- if eq .Values.gpu.vendor "nvidia" -}}
cuda
{{- else if eq .Values.gpu.vendor "amd" -}}
hip
{{- else if eq .Values.gpu.vendor "intel" -}}
sycl
{{- else -}}
cpu
{{- end }}
{{- end }}

{{/*
vmafx.env.controller — the vmafx-controller container (templates/controller.yaml).
*/}}
{{- define "vmafx.env.controller" }}
            - name: VMAFX_HTTP_ADDR
              value: ":{{ .Values.controller.httpPort }}"
            - name: VMAFX_GRPC_LISTEN
              value: ":{{ .Values.controller.grpcPort }}"
{{- if eq (include "vmafx.controllerStoreBackend" .) "postgres" }}
            - name: VMAFX_STORE_BACKEND
              value: postgres
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") (eq .Values.controller.store.postgresql.mode "external") }}
            - name: VMAFX_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.controller.store.postgresql.external.secretName | quote }}
                  key: {{ .Values.controller.store.postgresql.external.secretKey | default "uri" | quote }}
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") (ne .Values.controller.store.postgresql.mode "external") }}
            - name: VMAFX_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-app" (include "vmafx.controllerDatabaseCluster" .) | quote }}
                  key: uri
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") .Values.controller.store.backoffBase }}
            - name: VMAFX_STORE_BACKOFF_BASE
              value: {{ .Values.controller.store.backoffBase | quote }}
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") .Values.controller.store.backoffMax }}
            - name: VMAFX_STORE_BACKOFF_MAX
              value: {{ .Values.controller.store.backoffMax | quote }}
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") .Values.controller.store.leaseTTL }}
            - name: VMAFX_STORE_LEASE_TTL
              value: {{ .Values.controller.store.leaseTTL | quote }}
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") .Values.controller.store.sessionTTL }}
            - name: VMAFX_STORE_SESSION_TTL
              value: {{ .Values.controller.store.sessionTTL | quote }}
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") .Values.controller.store.sweepInterval }}
            - name: VMAFX_STORE_SWEEP_INTERVAL
              value: {{ .Values.controller.store.sweepInterval | quote }}
{{- end }}
{{- if ne (include "vmafx.controllerStoreBackend" .) "postgres" }}
            - name: VMAFX_DB_PATH
              value: /data/vmafx-controller.db
{{- end }}
            - name: VMAFX_AUTH_DISABLED
              value: {{ .Values.auth.disabled | toString | quote }}
{{- if eq (include "vmafx.tenantSource" .) "kubernetes" }}
            - name: VMAFX_AUTH_TENANTS_SOURCE
              value: "kubernetes"
{{- end }}
{{- if eq (include "vmafx.tenantSource" .) "kubernetes" }}
            - name: VMAFX_AUTH_TENANTS_NAMESPACE
              value: {{ .Release.Namespace | quote }}
{{- end }}
{{- if and (ne (include "vmafx.tenantSource" .) "kubernetes") .Values.auth.jwksEndpoint }}
            - name: VMAFX_JWKS_ENDPOINT
              value: {{ .Values.auth.jwksEndpoint | quote }}
{{- end }}
{{- if and (ne (include "vmafx.tenantSource" .) "kubernetes") .Values.auth.issuer }}
            - name: VMAFX_AUTH_ISSUER
              value: {{ .Values.auth.issuer | quote }}
{{- end }}
{{- if and (ne (include "vmafx.tenantSource" .) "kubernetes") .Values.auth.audience }}
            - name: VMAFX_AUTH_AUDIENCE
              value: {{ .Values.auth.audience | quote }}
{{- end }}
{{- if and (ne (include "vmafx.tenantSource" .) "kubernetes") .Values.auth.tenantClaim }}
            - name: VMAFX_AUTH_TENANT_CLAIM
              value: {{ .Values.auth.tenantClaim | quote }}
{{- end }}
{{- if and (ne (include "vmafx.tenantSource" .) "kubernetes") .Values.auth.rolesClaim }}
            - name: VMAFX_AUTH_ROLES_CLAIM
              value: {{ .Values.auth.rolesClaim | quote }}
{{- end }}
{{- if and (ne (include "vmafx.tenantSource" .) "kubernetes") .Values.auth.scoringRoots }}
            - name: VMAFX_SCORING_ROOTS
              value: {{ join "," .Values.auth.scoringRoots | quote }}
{{- end }}
{{- end }}

{{/*
vmafx.env.migrate — the controller's schema migration Job (vmafx.controllerMigrationPod).
*/}}
{{- define "vmafx.env.migrate" }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") (eq .Values.controller.store.postgresql.mode "external") }}
        - name: VMAFX_DB_DSN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.controller.store.postgresql.external.secretName | quote }}
              key: {{ .Values.controller.store.postgresql.external.secretKey | default "uri" | quote }}
{{- end }}
{{- if and (eq (include "vmafx.controllerStoreBackend" .) "postgres") (ne .Values.controller.store.postgresql.mode "external") }}
        - name: VMAFX_DB_DSN
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-app" (include "vmafx.controllerDatabaseCluster" .) | quote }}
              key: uri
{{- end }}
{{- end }}

{{/*
vmafx.env.operator — the vmafx-operator container (templates/operator-deployment.yaml).
*/}}
{{- define "vmafx.env.operator" }}
            - name: VMAFX_OPERATOR_METRICS_ADDR
              value: ":8080"
            - name: VMAFX_OPERATOR_HEALTH_PROBE_ADDR
              value: ":8081"
            - name: VMAFX_OPERATOR_LEADER_ELECTION
              value: {{ .Values.operator.leaderElect | default false | quote }}
            - name: VMAFX_LOG_LEVEL
              value: {{ .Values.operator.logLevel | default "info" | quote }}
{{- if .Values.controller.enabled }}
            # The chart's controller (ADR-1589): GetJob polls and /healthz probes.
            - name: VMAFX_CONTROLLER_GRPC_ADDR
              value: {{ printf "%s:%v" (include "vmafx.controllerHost" .) .Values.controller.grpcPort | quote }}
{{- end }}
{{- if .Values.controller.enabled }}
            - name: VMAFX_CONTROLLER_HTTP_ADDR
              value: {{ printf "http://%s:%v" (include "vmafx.controllerHost" .) .Values.controller.httpPort | quote }}
{{- end }}
{{- if .Values.operator.controllerToken.secretName }}
            # Bearer token of the GetJob polls, re-read on every poll.
            - name: VMAFX_CONTROLLER_TOKEN_FILE
              value: {{ include "vmafx.controllerTokenPath" . | quote }}
{{- end }}
{{- end }}

{{/*
vmafx.env.node — the vmafx-node container (templates/node.yaml).
*/}}
{{- define "vmafx.env.node" }}
{{- if include "vmafx.nodeControllerAddr" . }}
            # The node's controller client registers here and pulls jobs; unset
            # (no controller) the node serves direct scoring only.
            - name: VMAFX_CONTROLLER_ADDR
              value: {{ include "vmafx.nodeControllerAddr" . | quote }}
{{- end }}
{{- if .Values.node.controllerToken.secretName }}
            # Bearer token (vmafx:node), re-read on every call (ADR-1524).
            - name: VMAFX_CONTROLLER_TOKEN_FILE
              value: {{ include "vmafx.controllerTokenPath" . | quote }}
{{- end }}
            # The binary defaults grpc.listen to :50052 for standalone use.
            # Pin it explicitly to deploy's configurable grpcPort so the
            # ClusterIP Service and tcpSocket probes always follow chart values.
            - name: VMAFX_GRPC_LISTEN
              value: ":{{ .Values.node.grpcPort | default 50052 }}"
            # The HTTP listener of /metrics and the probe endpoints; pinned to
            # node.metricsPort so the container port, the Service port, the
            # NetworkPolicy and the node's ServiceMonitor follow chart values.
            - name: VMAFX_HTTP_ADDR
              value: ":{{ .Values.node.metricsPort | default 9090 }}"
            - name: VMAFX_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VMAFX_BACKEND
              value: {{ include "vmafx.backendEnvValue" . | quote }}
            # Storage / scoring env vars folded in from the legacy
            # templates/node-deployment.yaml (ADR-0719 rclone integration).
            - name: VMAFX_STORAGE_MODE
              value: {{ .Values.storage.mode | default "http-serve" | quote }}
{{- if include "vmafx.nodeMountRoot" . }}
            - name: VMAFX_STORAGE_MOUNT_ROOT
              value: {{ include "vmafx.nodeMountRoot" . | quote }}
{{- end }}
{{- if .Values.node.ebpf.enabled }}
            # eBPF descriptor tracker (ADR-1539); the node stops at startup
            # when the host cannot run it.
            - name: VMAFX_EBPF_BYPASS
              value: "1"
{{- end }}
{{- if .Values.node.ebpf.enabled }}
            - name: VMAFX_EBPF_MOUNT_PREFIX
              value: {{ .Values.node.ebpf.mountPrefix | quote }}
{{- end }}
{{- if .Values.storage.rclone.config }}
            # Only with the rclone Secret mounted below; without it rclone uses
            # its own defaults (on-the-fly remotes such as :s3,env_auth:).
            - name: VMAFX_RCLONE_CONFIG
              value: "/etc/vmafx/rclone.conf"
{{- end }}
            - name: VMAFX_VMAF_BINARY
              value: "/usr/local/bin/vmaf"
            # The models volume when it is mounted, else the models the node
            # image ships (persistence.models.mountPath always has a value).
            - name: VMAFX_MODEL_DIR
              value: {{ ternary .Values.persistence.models.mountPath "/usr/local/share/vmafx/model" .Values.persistence.models.enabled | quote }}
{{- end }}
