// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.
//
// The vmafx.dev/v1 API group (ADR-2350 D13). Change the definition and run
// `python3 scripts/codegen/vmafx-api.py --write`, then
// `python3 scripts/codegen/crd_generate.py --write` (deepcopy, CRDs, RBAC).

// Package v1 contains API schema definitions for the vmafx.dev/v1 API group.
//
// +kubebuilder:object:generate=true
// +groupName=vmafx.dev
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// GroupVersion is the group/version for this API.
	GroupVersion = schema.GroupVersion{Group: "vmafx.dev", Version: "v1"}

	// SchemeBuilder is used to add Go types to the GroupVersionKind scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

// deepCopier is a spec or status type of this group; controller-gen writes its
// DeepCopyInto.
type deepCopier[T any] interface {
	*T
	DeepCopyInto(out *T)
}

// deepCopyResource copies one custom resource into another: its type and
// object metadata, its spec and its status. Every resource's DeepCopyInto
// calls it, so the copy of a resource is written once (HISS-19).
func deepCopyResource[Spec, Status any, InSpec deepCopier[Spec], InStatus deepCopier[Status]](
	inType metav1.TypeMeta, inMeta *metav1.ObjectMeta, inSpec InSpec, inStatus InStatus,
	outType *metav1.TypeMeta, outMeta *metav1.ObjectMeta, outSpec *Spec, outStatus *Status,
) {
	*outType = inType
	inMeta.DeepCopyInto(outMeta)
	inSpec.DeepCopyInto(outSpec)
	inStatus.DeepCopyInto(outStatus)
}
