// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.
//
// Go types of the VmafxJob custom resource (ADR-2350 D13). Change the definition and run
// `python3 scripts/codegen/vmafx-api.py --write`, then
// `python3 scripts/codegen/crd_generate.py --write` (deepcopy, CRDs, RBAC).

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VmafxJobPhase enumerates the lifecycle phases of a VmafxJob.
//
// +kubebuilder:validation:Enum=Pending;Running;Succeeded;Failed
type VmafxJobPhase string

const (
	// VmafxJobPhasePending: The job has been accepted but not yet assigned to a
	// node.
	VmafxJobPhasePending VmafxJobPhase = "Pending"

	// VmafxJobPhaseRunning: The job runs on a node.
	VmafxJobPhaseRunning VmafxJobPhase = "Running"

	// VmafxJobPhaseSucceeded: The job completed successfully and a score is
	// available.
	VmafxJobPhaseSucceeded VmafxJobPhase = "Succeeded"

	// VmafxJobPhaseFailed: The job terminated with an error; see Message for
	// details.
	VmafxJobPhaseFailed VmafxJobPhase = "Failed"
)

// VmafxJobSpec defines the desired state of a VmafxJob.
type VmafxJobSpec struct {
	// Reference is the URI of the reference video. Supported schemes: file://,
	// s3://, rclone://.
	// +kubebuilder:validation:MinLength=1
	// +required
	Reference string `json:"reference"`

	// Distorted is the URI of the distorted video to compare against Reference.
	// +kubebuilder:validation:MinLength=1
	// +required
	Distorted string `json:"distorted"`

	// Model is the VMAF model to use (e.g. "vmaf_v0.6.1"). Defaults to the node's
	// default model when omitted.
	// +optional
	Model string `json:"model,omitempty"`

	// Backend selects the compute backend: cpu, cuda, sycl, hip, or metal.
	// +kubebuilder:validation:Enum=cpu;cuda;sycl;hip;metal
	// +kubebuilder:default:="cpu"
	// +optional
	Backend string `json:"backend,omitempty"`

	// Priority is a non-negative scheduling priority; higher values are dispatched
	// first.
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:default:=0
	// +optional
	Priority int32 `json:"priority,omitempty"`
}

// VmafxJobStatus defines the observed state of a VmafxJob.
type VmafxJobStatus struct {
	// Phase is the current lifecycle phase of the job.
	// +optional
	Phase VmafxJobPhase `json:"phase,omitempty"`

	// Score is the VMAF score produced by the job. Set only when Phase ==
	// Succeeded.
	// +optional
	Score float64 `json:"score,omitempty"`

	// AssignedNode is the name of the VmafxNode that is executing (or executed)
	// this job.
	// +optional
	AssignedNode string `json:"assignedNode,omitempty"`

	// ControllerJobID is the ID the vmafx-controller assigned to the job; the
	// reconciler polls GetJob with it. Empty until a controller accepted the job.
	// +optional
	ControllerJobID string `json:"controllerJobID,omitempty"`

	// StartedAt records when the job began running.
	// +optional
	StartedAt *metav1.Time `json:"startedAt,omitempty"`

	// FinishedAt records when the job reached a terminal phase (Succeeded or
	// Failed).
	// +optional
	FinishedAt *metav1.Time `json:"finishedAt,omitempty"`

	// Message is a human-readable explanation of the current phase; populated on
	// failure.
	// +optional
	Message string `json:"message,omitempty"`
}

// VmafxJob is the Schema for the vmafxjobs API: one reference/distorted pair
// scored against a chosen model on a chosen backend.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=vmjob
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase"
// +kubebuilder:printcolumn:name="Score",type="number",JSONPath=".status.score"
// +kubebuilder:printcolumn:name="Node",type="string",JSONPath=".status.assignedNode"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type VmafxJob struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VmafxJobSpec   `json:"spec,omitempty"`
	Status VmafxJobStatus `json:"status,omitempty"`
}

// DeepCopyInto copies the receiver into out through deepCopyResource;
// controller-gen writes DeepCopy and DeepCopyObject of VmafxJob around it.
func (in *VmafxJob) DeepCopyInto(out *VmafxJob) {
	deepCopyResource(in.TypeMeta, &in.ObjectMeta, &in.Spec, &in.Status,
		&out.TypeMeta, &out.ObjectMeta, &out.Spec, &out.Status)
}

// VmafxJobList contains a list of VmafxJob.
//
// +kubebuilder:object:root=true
type VmafxJobList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VmafxJob `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VmafxJob{}, &VmafxJobList{})
}
