// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.
//
// Go types of the VmafxTenant custom resource (ADR-2350 D13). Change the definition and run
// `python3 scripts/codegen/vmafx-api.py --write`, then
// `python3 scripts/codegen/crd_generate.py --write` (deepcopy, CRDs, RBAC).

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VmafxTenantSpec defines a tenant: its identity provider, its role policy and
// the inputs it may score.
type VmafxTenantSpec struct {
	// TenantID is the unique, stable identifier of the tenant. It must match the
	// "tid" (or configured tenant claim) in the OIDC tokens issued to this
	// tenant's users.
	// +kubebuilder:validation:Pattern=`^[a-z0-9][a-z0-9\-]{0,62}[a-z0-9]$`
	// +required
	TenantID string `json:"tenantId"`

	// Enabled false rejects every request of the tenant with 403, even with an
	// otherwise valid token: emergency suspension without revoking certificates.
	// +kubebuilder:default:=true
	// +optional
	Enabled *bool `json:"enabled,omitempty"`

	// OIDC configures the tenant's identity provider.
	// +required
	OIDC VmafxTenantOIDC `json:"oidc"`

	// RBAC is the tenant's role policy. The defaults enforce least privilege.
	// +optional
	RBAC *VmafxTenantRBAC `json:"rbac,omitempty"`

	// Scoring names the inputs the tenant's callers may score (ADR-1577).
	// +optional
	Scoring *VmafxTenantScoring `json:"scoring,omitempty"`
}

// VmafxTenantStatus defines the observed state of a VmafxTenant.
type VmafxTenantStatus struct {
	// Conditions are the latest observations of the tenant.
	// +optional
	Conditions []VmafxTenantCondition `json:"conditions,omitempty"`

	// ObservedGeneration is the generation the conditions describe.
	// +optional
	ObservedGeneration int64 `json:"observedGeneration,omitempty"`
}

// VmafxTenantOIDC is the OIDC provider configuration of a tenant.
type VmafxTenantOIDC struct {
	// Issuer is the expected "iss" claim: the canonical base URL of the identity
	// provider.
	// +kubebuilder:validation:Format=uri
	// +required
	Issuer string `json:"issuer"`

	// JWKSEndpoint is the URL of the provider's JWKS endpoint, from which the
	// RS256 public keys are fetched.
	// +kubebuilder:validation:Format=uri
	// +required
	JWKSEndpoint string `json:"jwksEndpoint"`

	// Audience is the expected "aud" claim. Empty skips the audience check (not
	// recommended in production).
	// +optional
	Audience string `json:"audience,omitempty"`

	// TenantClaim is the JWT claim that holds the tenant identifier.
	// +kubebuilder:default:="tid"
	// +optional
	TenantClaim string `json:"tenantClaim,omitempty"`

	// RolesClaim is the JWT claim that holds the list of vmafx roles
	// (vmafx:reader, vmafx:writer, vmafx:admin, vmafx:node).
	// +kubebuilder:default:="vmafx_roles"
	// +optional
	RolesClaim string `json:"rolesClaim,omitempty"`
}

// VmafxTenantRBAC is the role policy of a tenant.
type VmafxTenantRBAC struct {
	// DefaultRole is the role of an authenticated user whose token names no vmafx
	// role. vmafx:node is not offered: a compute node needs the role in its token.
	// +kubebuilder:validation:Enum=vmafx:reader;vmafx:writer;vmafx:admin
	// +kubebuilder:default:="vmafx:reader"
	// +optional
	DefaultRole string `json:"defaultRole,omitempty"`

	// AllowedRoles lists the roles the tenant's users may hold; other roles in a
	// token are dropped. vmafx:node is the compute node's role: it calls the node
	// API and nothing else. List it for a tenant that runs its own nodes.
	// +kubebuilder:validation:items:Enum=vmafx:reader;vmafx:writer;vmafx:admin;vmafx:node
	// +kubebuilder:default:={"vmafx:reader","vmafx:writer"}
	// +optional
	AllowedRoles []string `json:"allowedRoles,omitempty"`
}

// VmafxTenantScoring names the inputs a tenant's callers may score (ADR-1577).
type VmafxTenantScoring struct {
	// Roots are absolute directories (/data/acme), http(s) URL prefixes
	// (https://media.example.com/acme/) and rclone remote prefixes
	// (s3:bucket/acme, s3://bucket/acme). ".." is refused. Empty or absent: the
	// tenant may score nothing (deny by default).
	// +kubebuilder:validation:items:MinLength=1
	// +kubebuilder:validation:MaxItems=32
	// +optional
	Roots []string `json:"roots,omitempty"`
}

// VmafxTenantCondition is one observation about a tenant.
type VmafxTenantCondition struct {
	// Type is the condition type.
	// +required
	Type string `json:"type"`

	// Status is True, False or Unknown.
	// +kubebuilder:validation:Enum=True;False;Unknown
	// +required
	Status string `json:"status"`

	// Reason is a machine-readable reason for the status.
	// +optional
	Reason string `json:"reason,omitempty"`

	// Message is a human-readable explanation.
	// +optional
	Message string `json:"message,omitempty"`

	// LastTransitionTime is when the status last changed.
	// +optional
	LastTransitionTime *metav1.Time `json:"lastTransitionTime,omitempty"`
}

// VmafxTenant configures a named tenant's OIDC provider and RBAC policy for the
// vmafx-controller multi-tenant auth gateway (ADR-0794).
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=vmtenant
// +kubebuilder:printcolumn:name="Issuer",type="string",JSONPath=".spec.oidc.issuer"
// +kubebuilder:printcolumn:name="Enabled",type="boolean",JSONPath=".spec.enabled"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type VmafxTenant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VmafxTenantSpec   `json:"spec"`
	Status VmafxTenantStatus `json:"status,omitempty"`
}

// DeepCopyInto copies the receiver into out through deepCopyResource;
// controller-gen writes DeepCopy and DeepCopyObject of VmafxTenant around it.
func (in *VmafxTenant) DeepCopyInto(out *VmafxTenant) {
	deepCopyResource(in.TypeMeta, &in.ObjectMeta, &in.Spec, &in.Status,
		&out.TypeMeta, &out.ObjectMeta, &out.Spec, &out.Status)
}

// VmafxTenantList contains a list of VmafxTenant.
//
// +kubebuilder:object:root=true
type VmafxTenantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VmafxTenant `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VmafxTenant{}, &VmafxTenantList{})
}
