// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.
//
// Go types of the VmafxNode custom resource (ADR-2350 D13). Change the definition and run
// `python3 scripts/codegen/vmafx-api.py --write`, then
// `python3 scripts/codegen/crd_generate.py --write` (deepcopy, CRDs, RBAC).

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VmafxNodeSpec defines the desired state of a VmafxNode.
type VmafxNodeSpec struct {
	// GPUVendor is the device vendor of the node: nvidia, amd, intel or cpu.
	// +kubebuilder:validation:Enum=nvidia;amd;intel;cpu
	// +required
	GPUVendor string `json:"gpuVendor"`

	// Capacity is the number of jobs the node runs at once.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:default:=1
	// +optional
	Capacity int32 `json:"capacity,omitempty"`

	// Image overrides the node container image.
	// +optional
	Image string `json:"image,omitempty"`
}

// VmafxNodeStatus defines the observed state of a VmafxNode.
type VmafxNodeStatus struct {
	// Healthy is true while the node sends heartbeats.
	// +optional
	Healthy bool `json:"healthy,omitempty"`

	// LastHeartbeat records the node's last heartbeat.
	// +optional
	LastHeartbeat *metav1.Time `json:"lastHeartbeat,omitempty"`

	// AssignedJobs is the number of jobs the node runs.
	// +optional
	AssignedJobs int32 `json:"assignedJobs,omitempty"`

	// DetectedDevice names the device the node found.
	// +optional
	DetectedDevice string `json:"detectedDevice,omitempty"`
}

// VmafxNode is the Schema for the vmafxnodes API: a worker node of the platform
// and the device it scores on.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=vmnode
// +kubebuilder:printcolumn:name="Vendor",type="string",JSONPath=".spec.gpuVendor"
// +kubebuilder:printcolumn:name="Healthy",type="boolean",JSONPath=".status.healthy"
// +kubebuilder:printcolumn:name="Jobs",type="integer",JSONPath=".status.assignedJobs"
// +kubebuilder:printcolumn:name="Device",type="string",JSONPath=".status.detectedDevice"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type VmafxNode struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VmafxNodeSpec   `json:"spec,omitempty"`
	Status VmafxNodeStatus `json:"status,omitempty"`
}

// DeepCopyInto copies the receiver into out through deepCopyResource;
// controller-gen writes DeepCopy and DeepCopyObject of VmafxNode around it.
func (in *VmafxNode) DeepCopyInto(out *VmafxNode) {
	deepCopyResource(in.TypeMeta, &in.ObjectMeta, &in.Spec, &in.Status,
		&out.TypeMeta, &out.ObjectMeta, &out.Spec, &out.Status)
}

// VmafxNodeList contains a list of VmafxNode.
//
// +kubebuilder:object:root=true
type VmafxNodeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VmafxNode `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VmafxNode{}, &VmafxNodeList{})
}
