// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.
//
// Go types of the VmafxModelTraining custom resource (ADR-2350 D13). Change the definition and run
// `python3 scripts/codegen/vmafx-api.py --write`, then
// `python3 scripts/codegen/crd_generate.py --write` (deepcopy, CRDs, RBAC).

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VmafxModelTrainingPhase enumerates the lifecycle phases of a
// VmafxModelTraining.
//
// +kubebuilder:validation:Enum=Initializing;Running;Paused;Failed
type VmafxModelTrainingPhase string

const (
	// VmafxModelTrainingPhaseInitializing: The trainer is starting.
	VmafxModelTrainingPhaseInitializing VmafxModelTrainingPhase = "Initializing"

	// VmafxModelTrainingPhaseRunning: The trainer consumes samples.
	VmafxModelTrainingPhaseRunning VmafxModelTrainingPhase = "Running"

	// VmafxModelTrainingPhasePaused: Training is paused.
	VmafxModelTrainingPhasePaused VmafxModelTrainingPhase = "Paused"

	// VmafxModelTrainingPhaseFailed: Training stopped with an error.
	VmafxModelTrainingPhaseFailed VmafxModelTrainingPhase = "Failed"
)

// VmafxModelTrainingSpec defines the desired state of a VmafxModelTraining.
type VmafxModelTrainingSpec struct {
	// BaseModel is the model the training starts from.
	// +kubebuilder:validation:MinLength=1
	// +required
	BaseModel string `json:"baseModel"`

	// DataSource selects the samples.
	// +optional
	DataSource VmafxModelTrainingDataSource `json:"dataSource,omitempty"`

	// Algorithm is the training algorithm.
	// +kubebuilder:validation:Enum=online-sgd-ema
	// +required
	Algorithm string `json:"algorithm"`

	// Checkpoint sets when checkpoints are written.
	// +optional
	Checkpoint VmafxModelTrainingCheckpoint `json:"checkpoint,omitempty"`

	// OutputRegistry is the registry the trained models are pushed to.
	// +kubebuilder:validation:MinLength=1
	// +required
	OutputRegistry string `json:"outputRegistry"`
}

// VmafxModelTrainingStatus defines the observed state of a VmafxModelTraining.
type VmafxModelTrainingStatus struct {
	// CurrentSamples is the number of samples consumed so far.
	// +optional
	CurrentSamples int32 `json:"currentSamples,omitempty"`

	// LastCheckpoint records the last checkpoint.
	// +optional
	LastCheckpoint *metav1.Time `json:"lastCheckpoint,omitempty"`

	// ModelVersion names the newest trained model.
	// +optional
	ModelVersion string `json:"modelVersion,omitempty"`

	// Phase is the current lifecycle phase of the training.
	// +optional
	Phase VmafxModelTrainingPhase `json:"phase,omitempty"`
}

// VmafxModelTrainingDataSource selects the nodes whose scored samples feed the
// training.
type VmafxModelTrainingDataSource struct {
	// NodeSelector selects the VmafxNodes by label.
	// +optional
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
}

// VmafxModelTrainingCheckpoint sets when the trainer writes a checkpoint.
type VmafxModelTrainingCheckpoint struct {
	// Interval is the time between checkpoints.
	// +kubebuilder:default:="10m"
	// +optional
	Interval string `json:"interval,omitempty"`

	// MinSamples is the number of samples a checkpoint needs.
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:default:=1000
	// +optional
	MinSamples int32 `json:"minSamples,omitempty"`
}

// VmafxModelTraining is the Schema for the vmafxmodeltrainings API: an online
// training run that refines a base model from scored samples.
//
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=vmtrain
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase"
// +kubebuilder:printcolumn:name="Samples",type="integer",JSONPath=".status.currentSamples"
// +kubebuilder:printcolumn:name="ModelVersion",type="string",JSONPath=".status.modelVersion"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
type VmafxModelTraining struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   VmafxModelTrainingSpec   `json:"spec,omitempty"`
	Status VmafxModelTrainingStatus `json:"status,omitempty"`
}

// DeepCopyInto copies the receiver into out through deepCopyResource;
// controller-gen writes DeepCopy and DeepCopyObject of VmafxModelTraining
// around it.
func (in *VmafxModelTraining) DeepCopyInto(out *VmafxModelTraining) {
	deepCopyResource(in.TypeMeta, &in.ObjectMeta, &in.Spec, &in.Status,
		&out.TypeMeta, &out.ObjectMeta, &out.Spec, &out.Status)
}

// VmafxModelTrainingList contains a list of VmafxModelTraining.
//
// +kubebuilder:object:root=true
type VmafxModelTrainingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VmafxModelTraining `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VmafxModelTraining{}, &VmafxModelTrainingList{})
}
