//go:build !ignore_autogenerated

// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxJob.
func (in *VmafxJob) DeepCopy() *VmafxJob {
	if in == nil {
		return nil
	}
	out := new(VmafxJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxJobList) DeepCopyInto(out *VmafxJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VmafxJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxJobList.
func (in *VmafxJobList) DeepCopy() *VmafxJobList {
	if in == nil {
		return nil
	}
	out := new(VmafxJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxJobSpec) DeepCopyInto(out *VmafxJobSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxJobSpec.
func (in *VmafxJobSpec) DeepCopy() *VmafxJobSpec {
	if in == nil {
		return nil
	}
	out := new(VmafxJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxJobStatus) DeepCopyInto(out *VmafxJobStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxJobStatus.
func (in *VmafxJobStatus) DeepCopy() *VmafxJobStatus {
	if in == nil {
		return nil
	}
	out := new(VmafxJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxModelTraining.
func (in *VmafxModelTraining) DeepCopy() *VmafxModelTraining {
	if in == nil {
		return nil
	}
	out := new(VmafxModelTraining)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxModelTraining) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxModelTrainingCheckpoint) DeepCopyInto(out *VmafxModelTrainingCheckpoint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxModelTrainingCheckpoint.
func (in *VmafxModelTrainingCheckpoint) DeepCopy() *VmafxModelTrainingCheckpoint {
	if in == nil {
		return nil
	}
	out := new(VmafxModelTrainingCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxModelTrainingDataSource) DeepCopyInto(out *VmafxModelTrainingDataSource) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxModelTrainingDataSource.
func (in *VmafxModelTrainingDataSource) DeepCopy() *VmafxModelTrainingDataSource {
	if in == nil {
		return nil
	}
	out := new(VmafxModelTrainingDataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxModelTrainingList) DeepCopyInto(out *VmafxModelTrainingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VmafxModelTraining, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxModelTrainingList.
func (in *VmafxModelTrainingList) DeepCopy() *VmafxModelTrainingList {
	if in == nil {
		return nil
	}
	out := new(VmafxModelTrainingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxModelTrainingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxModelTrainingSpec) DeepCopyInto(out *VmafxModelTrainingSpec) {
	*out = *in
	in.DataSource.DeepCopyInto(&out.DataSource)
	out.Checkpoint = in.Checkpoint
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxModelTrainingSpec.
func (in *VmafxModelTrainingSpec) DeepCopy() *VmafxModelTrainingSpec {
	if in == nil {
		return nil
	}
	out := new(VmafxModelTrainingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxModelTrainingStatus) DeepCopyInto(out *VmafxModelTrainingStatus) {
	*out = *in
	if in.LastCheckpoint != nil {
		in, out := &in.LastCheckpoint, &out.LastCheckpoint
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxModelTrainingStatus.
func (in *VmafxModelTrainingStatus) DeepCopy() *VmafxModelTrainingStatus {
	if in == nil {
		return nil
	}
	out := new(VmafxModelTrainingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxNode.
func (in *VmafxNode) DeepCopy() *VmafxNode {
	if in == nil {
		return nil
	}
	out := new(VmafxNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxNodeList) DeepCopyInto(out *VmafxNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VmafxNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxNodeList.
func (in *VmafxNodeList) DeepCopy() *VmafxNodeList {
	if in == nil {
		return nil
	}
	out := new(VmafxNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxNodeSpec) DeepCopyInto(out *VmafxNodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxNodeSpec.
func (in *VmafxNodeSpec) DeepCopy() *VmafxNodeSpec {
	if in == nil {
		return nil
	}
	out := new(VmafxNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxNodeStatus) DeepCopyInto(out *VmafxNodeStatus) {
	*out = *in
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxNodeStatus.
func (in *VmafxNodeStatus) DeepCopy() *VmafxNodeStatus {
	if in == nil {
		return nil
	}
	out := new(VmafxNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenant.
func (in *VmafxTenant) DeepCopy() *VmafxTenant {
	if in == nil {
		return nil
	}
	out := new(VmafxTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxTenantCondition) DeepCopyInto(out *VmafxTenantCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenantCondition.
func (in *VmafxTenantCondition) DeepCopy() *VmafxTenantCondition {
	if in == nil {
		return nil
	}
	out := new(VmafxTenantCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxTenantList) DeepCopyInto(out *VmafxTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VmafxTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenantList.
func (in *VmafxTenantList) DeepCopy() *VmafxTenantList {
	if in == nil {
		return nil
	}
	out := new(VmafxTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VmafxTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxTenantOIDC) DeepCopyInto(out *VmafxTenantOIDC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenantOIDC.
func (in *VmafxTenantOIDC) DeepCopy() *VmafxTenantOIDC {
	if in == nil {
		return nil
	}
	out := new(VmafxTenantOIDC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxTenantRBAC) DeepCopyInto(out *VmafxTenantRBAC) {
	*out = *in
	if in.AllowedRoles != nil {
		in, out := &in.AllowedRoles, &out.AllowedRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenantRBAC.
func (in *VmafxTenantRBAC) DeepCopy() *VmafxTenantRBAC {
	if in == nil {
		return nil
	}
	out := new(VmafxTenantRBAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxTenantScoring) DeepCopyInto(out *VmafxTenantScoring) {
	*out = *in
	if in.Roots != nil {
		in, out := &in.Roots, &out.Roots
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenantScoring.
func (in *VmafxTenantScoring) DeepCopy() *VmafxTenantScoring {
	if in == nil {
		return nil
	}
	out := new(VmafxTenantScoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxTenantSpec) DeepCopyInto(out *VmafxTenantSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	out.OIDC = in.OIDC
	if in.RBAC != nil {
		in, out := &in.RBAC, &out.RBAC
		*out = new(VmafxTenantRBAC)
		(*in).DeepCopyInto(*out)
	}
	if in.Scoring != nil {
		in, out := &in.Scoring, &out.Scoring
		*out = new(VmafxTenantScoring)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenantSpec.
func (in *VmafxTenantSpec) DeepCopy() *VmafxTenantSpec {
	if in == nil {
		return nil
	}
	out := new(VmafxTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmafxTenantStatus) DeepCopyInto(out *VmafxTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]VmafxTenantCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmafxTenantStatus.
func (in *VmafxTenantStatus) DeepCopy() *VmafxTenantStatus {
	if in == nil {
		return nil
	}
	out := new(VmafxTenantStatus)
	in.DeepCopyInto(out)
	return out
}
