// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.

package main

// compoundKeys are the configuration keys of vmafx-node whose own name
// holds an underscore. golusoris turns every underscore of a VMAFX_ variable
// into the key delimiter except in these keys, so VMAFX_CONTROLLER_CA_FILE
// reaches controller.ca_file (ADR-2350 D13; the [[config]] entries of
// api/vmafx-platform.toml).
var compoundKeys = []string{
	"controller.ca_file",
	"controller.heartbeat_interval",
	"controller.poll_interval",
	"controller.rpc_timeout",
	"controller.server_name",
	"controller.token_file",
	"ebpf.mount_prefix",
	"grpc.cert_file",
	"grpc.key_file",
	"grpc.max_recv_size",
	"grpc.max_send_size",
	"storage.mount_root",
}
