/*
 * vmafx_rs_predict.h - C ABI of the Rust model predictor (ADR-1713).
 * Generated by cbindgen from core/src/rust/predict/src/abi.rs; regenerate with
 * scripts/dev/rust-abi-header.sh. DO NOT EDIT.
 *
 * Copyright 2026 Lusoris
 * SPDX-License-Identifier: EUPL-1.2
 */

#ifndef VMAFX_RS_PREDICT_H
#define VMAFX_RS_PREDICT_H

#include <stddef.h>
#include <stdint.h>

/*
 Opaque handle owned by Rust: `vmafx_rs_model_new` .. `vmafx_rs_model_free`.
 */
typedef struct VmafxRsModel VmafxRsModel;

/*
 Flat view of a `VmafModel` and its `svm_model`. Every pointer is borrowed
 for the duration of `vmafx_rs_model_new` only; Rust copies what it keeps.
 Flags are 0 / 1.
 */
typedef struct VmafxRsModelView {
  /*
   `VmafModelNormalizationType`
   */
  uint32_t norm_type;
  double slope;
  double intercept;
  uint32_t n_features;
  const double *feature_slope;
  const double *feature_intercept;
  /*
   `strstr(name, "adm3") != NULL`, one byte per feature
   */
  const uint8_t *feature_guiding;
  /*
   `strstr(name, "speed_chroma") != NULL`, one byte per feature
   */
  const uint8_t *feature_guided;
  /*
   `chroma_from_luma.enabled && chroma_correction_parameter != 0`
   */
  uint32_t chroma_enabled;
  double chroma_parameter;
  uint32_t transform_enabled;
  uint32_t p0_enabled;
  double p0;
  uint32_t p1_enabled;
  double p1;
  uint32_t p2_enabled;
  double p2;
  uint32_t knots_enabled;
  uint32_t n_knots;
  const double *knot_x;
  const double *knot_y;
  uint32_t out_lte_in;
  uint32_t out_gte_in;
  uint32_t clip_enabled;
  double clip_min;
  double clip_max;
  /*
   `svm_parameter.svm_type`
   */
  int32_t svm_type;
  /*
   `svm_parameter.kernel_type`
   */
  int32_t kernel_type;
  int32_t degree;
  double gamma;
  double coef0;
  /*
   `model->l`
   */
  uint32_t n_sv;
  /*
   `model->sv_coef[0]`, `n_sv` values
   */
  const double *sv_coef;
  /*
   `model->rho[0]`
   */
  double rho;
  /*
   `n_sv + 1` offsets into the node arrays
   */
  const uint32_t *sv_start;
  uint32_t n_nodes;
  const int32_t *sv_index;
  const double *sv_value;
} VmafxRsModelView;

/*
 Failure detail of `vmafx_rs_model_predict` (status `VMAFX_RS_E_NONFINITE`).
 */
typedef struct VmafxRsPredictFail {
  /*
   0 model score, 1 score transform, 2 piecewise score
   */
  uint32_t stage;
  double value;
} VmafxRsPredictFail;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Builds the predictor from `view`; `*out` receives the handle.

 Returns `VMAFX_RS_OK`, `VMAFX_RS_E_NOTSUP` (a model the Rust predictor does
 not implement: the caller runs the C predictor and says so),
 `VMAFX_RS_E_INVAL` or `VMAFX_RS_E_NOMEM`.

 # Safety
 `view` points to a `VmafxRsModelView` whose pointers are valid for reads of
 the lengths its counts give, for the duration of the call; `out` is valid
 for one pointer write.
 */
int32_t vmafx_rs_model_new(const struct VmafxRsModelView *view, struct VmafxRsModel **out);

/*
 Predicts one frame from the raw feature scores in model order.

 `nodes` is caller scratch of `n_nodes >= n_features + 1` entries laid out as
 `struct svm_node` (`{ int index; double value; }`, 16 bytes); the predictor does not
 allocate. `fail` may be NULL; on `VMAF_RS_E_NONFINITE` it receives the stage
 and the offending value.

 # Safety
 `model` came from `vmafx_rs_model_new` and is not freed during the call;
 `scores` is valid for `n_scores` reads, `nodes` for `n_nodes` reads and
 writes with no other thread using it, `out` for one write, `fail` NULL or
 valid for one write.
 */
int32_t vmafx_rs_model_predict(const struct VmafxRsModel *model, const double *scores, size_t n_scores, uint32_t flags, void *nodes, size_t n_nodes, double *out, struct VmafxRsPredictFail *fail);

/*
 Frees a handle from `vmafx_rs_model_new`; NULL is a no-op.

 # Safety
 `model` is NULL or a handle not yet freed, and no call uses it afterwards.
 */
void vmafx_rs_model_free(struct VmafxRsModel *model);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VMAFX_RS_PREDICT_H */
