// SPDX-License-Identifier: EUPL-1.2
// Copyright 2026 Lusoris

// Code generated by scripts/codegen/vmafx-api.py from api/vmafx-platform.toml. DO NOT EDIT.

package main

// compoundKeys are the configuration keys of vmafx-operator whose own name
// holds an underscore. golusoris turns every underscore of a VMAFX_ variable
// into the key delimiter except in these keys, so VMAFX_CONTROLLER_CA_FILE
// reaches controller.ca_file (ADR-2350 D13; the [[config]] entries of
// api/vmafx-platform.toml).
var compoundKeys = []string{
	"controller.ca_file",
	"controller.server_name",
	"controller.token_file",
	"operator.graceful_shutdown",
	"operator.health_probe_addr",
	"operator.leader_election",
	"operator.leader_election_id",
	"operator.metrics_addr",
	"operator.webhook_host",
	"operator.webhook_port",
}
