/**
 *  Copyright 2026 Lusoris
 *  SPDX-License-Identifier: EUPL-1.2
 *
 *  Elementary functions on fp32 pairs for SYCL kernels that have to follow a
 *  host computation done in fp64 (ADR-0220: no fp64 type on the device).
 *
 *  A pair (hi + lo, sycl_exact_fp.h) carries about 48 significant bits. The
 *  functions here return their result to about 2^-44 of its value. That is
 *  not fp64: a value the host rounds from fp64 to fp32 comes out the same
 *  unless it lies within about 2^-20 of an fp32 step of a rounding boundary,
 *  roughly one result in a million. A twin built on these is close to the
 *  host to that degree, not bit-identical; where bit-identity is required
 *  the reference's fp64 operations have to be replayed exactly
 *  (sycl_soft_double.h), which no math-library call allows.
 *
 *  Every function assumes its translation unit is compiled with contraction
 *  off, like sycl_exact_fp.h. Tables are read from device memory the caller
 *  filled from kAtanTable / kSinCosTable: a constant array indexed at run
 *  time inside a kernel is scratch memory (ADR-1395). This header must not
 *  mention the fp64 type.
 *
 *  The constants and tables are generated by scripts/dev/gen_sycl_ff_math.py.
 */

#ifndef VMAF_FEATURE_SYCL_SYCL_FF_MATH_H_
#define VMAF_FEATURE_SYCL_SYCL_FF_MATH_H_

#include <sycl/sycl.hpp>

#include <cstdint>

#include "sycl_compat.h"
#include "sycl_exact_fp.h"

namespace vmaf_sycl_ffm
{

using vmaf_sycl_exact::Ff;
using vmaf_sycl_exact::ff_add;
using vmaf_sycl_exact::ff_mul;
using vmaf_sycl_exact::ff_neg;
using vmaf_sycl_exact::quick_two_sum;
using vmaf_sycl_exact::two_prod;
using vmaf_sycl_exact::two_sum;

/* ------------------------------------------------------------------ */
/* Generated constants (scripts/dev/gen_sycl_ff_math.py)               */
/* ------------------------------------------------------------------ */

// BEGIN GENERATED
// clang-format off
/* NOLINTBEGIN(modernize-use-std-numbers): generated parts of pairs and
 * triples. std::numbers has no pairs, and the high word of a pair must be
 * the literal its low word was computed against (ADR-1436). */
/* pi / 16 and ln 2 in three parts. The first has 13 significant bits, so
 * its product with an integer below 2^11 is exact. */
inline constexpr float kPi16A = 0x1.921p-3f;
inline constexpr float kPi16B = 0x1.f6a888p-16f;
inline constexpr float kPi16C = 0x1.68c234p-42f;
inline constexpr float kLn2A = 0x1.62ep-1f;
inline constexpr float kLn2B = 0x1.0bfbe8p-15f;
inline constexpr float kLn2C = 0x1.cf79acp-40f;
inline constexpr float kSixteenOverPi = 0x1.45f306p+2f;
inline constexpr float kInvLn2 = 0x1.715476p+0f;
inline constexpr Ff kPi = {.hi = 0x1.921fb6p+1f, .lo = -0x1.777a5cp-24f};
inline constexpr Ff kHalfPi = {.hi = 0x1.921fb6p+0f, .lo = -0x1.777a5cp-25f};
inline constexpr Ff kThird = {.hi = 0x1.555556p-2f, .lo = -0x1.555556p-27f};
inline constexpr Ff kFifth = {.hi = 0x1.99999ap-3f, .lo = -0x1.99999ap-29f};
inline constexpr Ff kSixth = {.hi = 0x1.555556p-3f, .lo = -0x1.555556p-28f};
inline constexpr Ff kOne24 = {.hi = 0x1.555556p-5f, .lo = -0x1.555556p-30f};
inline constexpr Ff kOne120 = {.hi = 0x1.111112p-7f, .lo = -0x1.dddddep-32f};

/* 1 / n! for exp(): pairs where the term needs them, fp32 beyond. */
inline constexpr Ff kInvF3 = {.hi = 0x1.555556p-3f, .lo = -0x1.555556p-28f};
inline constexpr Ff kInvF4 = {.hi = 0x1.555556p-5f, .lo = -0x1.555556p-30f};
inline constexpr Ff kInvF5 = {.hi = 0x1.111112p-7f, .lo = -0x1.dddddep-32f};
inline constexpr Ff kInvF6 = {.hi = 0x1.6c16c2p-10f, .lo = -0x1.27d27ep-35f};
inline constexpr Ff kInvF7 = {.hi = 0x1.a01a02p-13f, .lo = -0x1.7f97fap-39f};
inline constexpr float kInvF8 = 0x1.a01a02p-16f;
inline constexpr float kInvF9 = 0x1.71de3ap-19f;
inline constexpr float kInvF10 = 0x1.27e4fcp-22f;
inline constexpr float kInvF11 = 0x1.ae6456p-26f;
inline constexpr float kInvF12 = 0x1.1eed8ep-29f;
inline constexpr float kInvF13 = 0x1.612462p-33f;
inline constexpr float kInvF14 = 0x1.93974ap-37f;

/* atan(j / 16), j = 0 .. 16, as (hi, lo). */
inline constexpr float kAtanTable[2 * 17] = {
    0.0f, 0.0f,
    0x1.ff55bcp-5f, -0x1.1a6042p-30f,
    0x1.fd5baap-4f, -0x1.54f424p-30f,
    0x1.7b97b4p-3f, 0x1.79cb6p-28f,
    0x1.f5b76p-3f, -0x1.b4dfc8p-29f,
    0x1.362774p-2f, -0x1.1f0286p-27f,
    0x1.6f6194p-2f, 0x1.e4defp-30f,
    0x1.a64eecp-2f, 0x1.e611fep-29f,
    0x1.dac67p-2f, 0x1.586ed4p-28f,
    0x1.0657eap-1f, -0x1.6499e6p-26f,
    0x1.1e00bap-1f, 0x1.7bdfd6p-26f,
    0x1.345f02p-1f, -0x1.98e422p-28f,
    0x1.4978fap-1f, 0x1.934f7p-28f,
    0x1.5d5898p-1f, 0x1.c5a6c6p-27f,
    0x1.700a7cp-1f, 0x1.5e118cp-27f,
    0x1.819d0cp-1f, -0x1.1d4eb6p-26f,
    0x1.921fb6p-1f, -0x1.777a5cp-26f,
};

/* sin(k pi / 16) and cos(k pi / 16), k = 0 .. 31, as
 * (sin hi, sin lo, cos hi, cos lo). */
inline constexpr float kSinCosTable[4 * 32] = {
    0.0f, 0.0f, 0x1p+0f, 0.0f,
    0x1.8f8b84p-3f, -0x1.cb2cfap-30f, 0x1.f6297cp-1f, 0x1.feeb96p-26f,
    0x1.87de2ap-2f, 0x1.abaa58p-28f, 0x1.d906bcp-1f, 0x1.e651a8p-26f,
    0x1.1c73b4p-1f, -0x1.9465cep-27f, 0x1.a9b662p-1f, 0x1.21d434p-26f,
    0x1.6a09e6p-1f, 0x1.9fcef4p-27f, 0x1.6a09e6p-1f, 0x1.9fcef4p-27f,
    0x1.a9b662p-1f, 0x1.21d434p-26f, 0x1.1c73b4p-1f, -0x1.9465cep-27f,
    0x1.d906bcp-1f, 0x1.e651a8p-26f, 0x1.87de2ap-2f, 0x1.abaa58p-28f,
    0x1.f6297cp-1f, 0x1.feeb96p-26f, 0x1.8f8b84p-3f, -0x1.cb2cfap-30f,
    0x1p+0f, 0.0f, 0.0f, 0.0f,
    0x1.f6297cp-1f, 0x1.feeb96p-26f, -0x1.8f8b84p-3f, 0x1.cb2cfap-30f,
    0x1.d906bcp-1f, 0x1.e651a8p-26f, -0x1.87de2ap-2f, -0x1.abaa58p-28f,
    0x1.a9b662p-1f, 0x1.21d434p-26f, -0x1.1c73b4p-1f, 0x1.9465cep-27f,
    0x1.6a09e6p-1f, 0x1.9fcef4p-27f, -0x1.6a09e6p-1f, -0x1.9fcef4p-27f,
    0x1.1c73b4p-1f, -0x1.9465cep-27f, -0x1.a9b662p-1f, -0x1.21d434p-26f,
    0x1.87de2ap-2f, 0x1.abaa58p-28f, -0x1.d906bcp-1f, -0x1.e651a8p-26f,
    0x1.8f8b84p-3f, -0x1.cb2cfap-30f, -0x1.f6297cp-1f, -0x1.feeb96p-26f,
    0.0f, 0.0f, -0x1p+0f, 0.0f,
    -0x1.8f8b84p-3f, 0x1.cb2cfap-30f, -0x1.f6297cp-1f, -0x1.feeb96p-26f,
    -0x1.87de2ap-2f, -0x1.abaa58p-28f, -0x1.d906bcp-1f, -0x1.e651a8p-26f,
    -0x1.1c73b4p-1f, 0x1.9465cep-27f, -0x1.a9b662p-1f, -0x1.21d434p-26f,
    -0x1.6a09e6p-1f, -0x1.9fcef4p-27f, -0x1.6a09e6p-1f, -0x1.9fcef4p-27f,
    -0x1.a9b662p-1f, -0x1.21d434p-26f, -0x1.1c73b4p-1f, 0x1.9465cep-27f,
    -0x1.d906bcp-1f, -0x1.e651a8p-26f, -0x1.87de2ap-2f, -0x1.abaa58p-28f,
    -0x1.f6297cp-1f, -0x1.feeb96p-26f, -0x1.8f8b84p-3f, 0x1.cb2cfap-30f,
    -0x1p+0f, 0.0f, 0.0f, 0.0f,
    -0x1.f6297cp-1f, -0x1.feeb96p-26f, 0x1.8f8b84p-3f, -0x1.cb2cfap-30f,
    -0x1.d906bcp-1f, -0x1.e651a8p-26f, 0x1.87de2ap-2f, 0x1.abaa58p-28f,
    -0x1.a9b662p-1f, -0x1.21d434p-26f, 0x1.1c73b4p-1f, -0x1.9465cep-27f,
    -0x1.6a09e6p-1f, -0x1.9fcef4p-27f, 0x1.6a09e6p-1f, 0x1.9fcef4p-27f,
    -0x1.1c73b4p-1f, 0x1.9465cep-27f, 0x1.a9b662p-1f, 0x1.21d434p-26f,
    -0x1.87de2ap-2f, -0x1.abaa58p-28f, 0x1.d906bcp-1f, 0x1.e651a8p-26f,
    -0x1.8f8b84p-3f, 0x1.cb2cfap-30f, 0x1.f6297cp-1f, 0x1.feeb96p-26f,
};
/* NOLINTEND(modernize-use-std-numbers) */
// clang-format on
// END GENERATED

inline constexpr unsigned kAtanTableFloats = 2u * 17u;
inline constexpr unsigned kSinCosTableFloats = 4u * 32u;

/* The two tables in device memory. */
struct Tables {
    const float *atan;    /* kAtanTable */
    const float *sin_cos; /* kSinCosTable */
};

/* ------------------------------------------------------------------ */
/* Pair arithmetic beyond sycl_exact_fp.h                              */
/* ------------------------------------------------------------------ */

VMAF_SYCL_ALWAYS_INLINE Ff from_float(float x)
{
    return {.hi = x, .lo = 0.0f};
}

/* The pair rounded to fp32, once. */
VMAF_SYCL_ALWAYS_INLINE float to_float(Ff a)
{
    return a.hi + a.lo;
}

VMAF_SYCL_ALWAYS_INLINE Ff sub(Ff a, Ff b)
{
    return ff_add(a, ff_neg(b));
}

VMAF_SYCL_ALWAYS_INLINE Ff add_f(Ff a, float b)
{
    const Ff sum = two_sum(a.hi, b);
    return quick_two_sum(sum.hi, sum.lo + a.lo);
}

VMAF_SYCL_ALWAYS_INLINE Ff mul_f(Ff a, float b)
{
    const Ff product = two_prod(a.hi, b);
    const float cross = a.lo * b;
    return quick_two_sum(product.hi, product.lo + cross);
}

VMAF_SYCL_ALWAYS_INLINE Ff square(Ff a)
{
    const Ff product = two_prod(a.hi, a.hi);
    const float cross = a.hi * a.lo;
    return quick_two_sum(product.hi, product.lo + (cross + cross));
}

/* a * p for a power of two p: exact. */
VMAF_SYCL_ALWAYS_INLINE Ff scale(Ff a, float power_of_two)
{
    return {.hi = a.hi * power_of_two, .lo = a.lo * power_of_two};
}

VMAF_SYCL_ALWAYS_INLINE bool less(Ff a, Ff b)
{
    return a.hi < b.hi || (a.hi == b.hi && a.lo < b.lo);
}

/* a / b for a non-zero b. The two partial quotients need not be correctly
 * rounded: what the first leaves, the second takes from the exact residual.
 * So this is the device's own division twice, where sycl_exact_fp.h's
 * ff_div() pays for two correctly rounded ones. */
VMAF_SYCL_ALWAYS_INLINE Ff div(Ff a, Ff b)
{
    const float q1 = a.hi / b.hi;
    const Ff residual = sub(a, mul_f(b, q1));
    const float q2 = residual.hi / b.hi;
    return quick_two_sum(q1, q2);
}

/* The square root of a non-negative pair: the device's fp32 root and one
 * Newton correction from the exact residual. As in div(), the root need not
 * be correctly rounded. */
VMAF_SYCL_ALWAYS_INLINE Ff sqrt(Ff a)
{
    if (!(a.hi > 0.0f)) {
        return {.hi = 0.0f, .lo = 0.0f};
    }
    const float root = sycl::sqrt(a.hi);
    const Ff residual = sub(a, two_prod(root, root));
    const float correction = residual.hi / (root + root);
    return quick_two_sum(root, correction);
}

/* ------------------------------------------------------------------ */
/* Roots and powers                                                    */
/* ------------------------------------------------------------------ */

/* x^(1/n) from an fp32 estimate y by one Halley step,
 *   y * ((n - 1) y^n + (n + 1) x) / ((n + 1) y^n + (n - 1) x),
 * whose error is the cube of the estimate's. `yn` is y^n. */
VMAF_SYCL_ALWAYS_INLINE Ff halley_root(Ff x, float y, Ff yn, float n)
{
    const Ff numerator = ff_add(mul_f(yn, n - 1.0f), mul_f(x, n + 1.0f));
    const Ff denominator = ff_add(mul_f(yn, n + 1.0f), mul_f(x, n - 1.0f));
    return mul_f(div(numerator, denominator), y);
}

/* x^(1/3) for x > 0. */
VMAF_SYCL_ALWAYS_INLINE Ff cbrt(Ff x)
{
    const float y = sycl::cbrt(x.hi);
    const Ff y3 = mul_f(two_prod(y, y), y);
    return halley_root(x, y, y3, 3.0f);
}

/* x^2.4 for x > 0: the square of x times its fifth root. */
VMAF_SYCL_ALWAYS_INLINE Ff pow_2_4(Ff x)
{
    const float y = sycl::pow(x.hi, 0.2f);
    const Ff y5 = mul_f(square(two_prod(y, y)), y);
    const Ff root = halley_root(x, y, y5, 5.0f);
    return square(ff_mul(x, root));
}

/* x^7. */
VMAF_SYCL_ALWAYS_INLINE Ff pow_7(float x)
{
    const Ff x2 = two_prod(x, x);
    const Ff x4 = square(x2);
    return mul_f(ff_mul(x4, x2), x);
}

/* ------------------------------------------------------------------ */
/* exp                                                                 */
/* ------------------------------------------------------------------ */

/* e^x = 2^k e^r with |r| <= ln(2) / 2. The exponent k is returned apart: for
 * a large negative x the result is below the fp32 range and only its product
 * with something else is representable. */
struct Exp {
    Ff value; /* e^r, in [0.70, 1.42] */
    int k;
};

VMAF_SYCL_ALWAYS_INLINE Exp exp(float x)
{
    const float k = sycl::rint(x * kInvLn2);
    Ff r = sub(from_float(x), two_prod(k, kLn2A));
    r = sub(r, two_prod(k, kLn2B));
    r = add_f(r, -(k * kLn2C));
    /* Terms 8 to 14 are below 2^-27 of the result: fp32 is enough there. */
    float tail = kInvF14;
    tail = tail * r.hi + kInvF13;
    tail = tail * r.hi + kInvF12;
    tail = tail * r.hi + kInvF11;
    tail = tail * r.hi + kInvF10;
    tail = tail * r.hi + kInvF9;
    tail = tail * r.hi + kInvF8;
    Ff p = add_f(kInvF7, tail * r.hi);
    p = ff_add(ff_mul(p, r), kInvF6);
    p = ff_add(ff_mul(p, r), kInvF5);
    p = ff_add(ff_mul(p, r), kInvF4);
    p = ff_add(ff_mul(p, r), kInvF3);
    p = add_f(ff_mul(p, r), 0.5f);
    p = add_f(ff_mul(p, r), 1.0f);
    p = add_f(ff_mul(p, r), 1.0f);
    return {.value = p, .k = (int)k};
}

/* ------------------------------------------------------------------ */
/* sin and cos                                                         */
/* ------------------------------------------------------------------ */

struct SinCos {
    Ff sin;
    Ff cos;
};

/* sin(x) and cos(x) for |x| below about 400: x = k pi / 16 + r with
 * |r| <= pi / 32, the functions of k pi / 16 from the table, those of r from
 * their series. */
VMAF_SYCL_ALWAYS_INLINE SinCos sin_cos(Ff x, const float *table)
{
    const float k = sycl::rint(x.hi * kSixteenOverPi);
    Ff r = sub(x, two_prod(k, kPi16A));
    r = sub(r, two_prod(k, kPi16B));
    r = add_f(r, -(k * kPi16C));
    const Ff z = square(r);
    /* sin(r) = r + r z (-1/6 + z (1/120 + z (-1/5040 + z / 362880))) */
    const float sin_tail = -0x1.a01a02p-13f + z.hi * 0x1.71de3ap-19f;
    Ff s = add_f(kOne120, z.hi * sin_tail);
    s = sub(ff_mul(s, z), kSixth);
    const Ff sin_r = ff_add(r, ff_mul(r, ff_mul(s, z)));
    /* cos(r) = 1 + z (-1/2 + z (1/24 + z (-1/720 + z (1/40320 - z / 3628800)))) */
    const float cos_tail = -0x1.6c16c2p-10f + z.hi * (0x1.a01a02p-16f + z.hi * -0x1.27e4fcp-22f);
    Ff c = add_f(kOne24, z.hi * cos_tail);
    c = add_f(ff_mul(c, z), -0.5f);
    const Ff cos_r = add_f(ff_mul(c, z), 1.0f);

    const size_t index = (size_t)((int)k & 31) * 4u;
    const Ff sin_k = {.hi = table[index + 0u], .lo = table[index + 1u]};
    const Ff cos_k = {.hi = table[index + 2u], .lo = table[index + 3u]};
    return {.sin = ff_add(ff_mul(sin_k, cos_r), ff_mul(cos_k, sin_r)),
            .cos = sub(ff_mul(cos_k, cos_r), ff_mul(sin_k, sin_r))};
}

/* ------------------------------------------------------------------ */
/* atan2                                                               */
/* ------------------------------------------------------------------ */

/* The angle of the point (x, y) in (-pi, pi], for fp32 coordinates that are
 * not both zero: the smaller coordinate over the larger is t in [0, 1],
 * atan(t) = atan(j / 16) + atan((t - j / 16) / (1 + t j / 16)) with the first
 * term from the table and the second, below 1 / 32, from its series. */
VMAF_SYCL_ALWAYS_INLINE Ff atan2(float y, float x, const float *table)
{
    const float ax = sycl::fabs(x);
    const float ay = sycl::fabs(y);
    const bool steep = ay > ax;
    const float small = steep ? ax : ay;
    const float large = steep ? ay : ax;
    const Ff t = div(from_float(small), from_float(large));
    const float j = sycl::rint(t.hi * 16.0f);
    const float c = j * 0.0625f;
    const Ff u = div(add_f(t, -c), add_f(mul_f(t, c), 1.0f));
    const Ff z = square(u);
    /* atan(u) = u + u z (-1/3 + z (1/5 + z (-1/7 + z / 9))) */
    const float tail = -0x1.24924ap-3f + z.hi * 0x1.c71c72p-4f;
    Ff p = add_f(kFifth, z.hi * tail);
    p = sub(ff_mul(p, z), kThird);
    const Ff atan_u = ff_add(u, ff_mul(u, ff_mul(p, z)));
    const size_t index = (size_t)(int)j * 2u;
    Ff angle = ff_add(Ff{.hi = table[index], .lo = table[index + 1u]}, atan_u);
    if (steep) {
        angle = sub(kHalfPi, angle);
    }
    if (x < 0.0f) {
        angle = sub(kPi, angle);
    }
    if (y < 0.0f) {
        angle = ff_neg(angle);
    }
    return angle;
}

} // namespace vmaf_sycl_ffm

#endif /* VMAF_FEATURE_SYCL_SYCL_FF_MATH_H_ */
