#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Generate and check the Go bindings of the protobuf files (ADR-2350 D13).

Usage::

    python3 scripts/codegen/proto_generate.py --write   # regenerate gen/go
    python3 scripts/codegen/proto_generate.py --check   # fail on any difference
    python3 scripts/codegen/proto_generate.py --check --breaking-against origin/master

The protobuf files under proto/ are themselves generated by
scripts/codegen/vmafx-api.py from api/vmafx-platform.toml and
core/api/vmafx.toml. This script runs buf, the release BUF_VERSION of
build-config.env through `go run` (the Go module checksum database verifies
it), with the repository's buf.yaml and buf.gen.yaml: `buf lint`, then `buf
generate` into a scratch directory, then the HISS-09 proofs of
scripts/proto/postprocess_gen_go.py, and writes or compares every *.pb.go under
gen/go. The protoc plugins are the versions go.mod pins as tools.
--breaking-against REF also runs `buf breaking` (WIRE_JSON) against the
protobuf files of REF.

When Go or the module proxy is unavailable, --check exits 77 and says why, so
a gate that did not run is never reported as passing.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from sqlc_generate import build_config

REPO = Path(__file__).resolve().parents[2]
SKIP = 77
BUF_MODULE = "github.com/bufbuild/buf/cmd/buf"
POSTPROCESS = Path("scripts/proto/postprocess_gen_go.py")
GENERATED = Path("gen/go")
TOOL_TIMEOUT_S = 900


class Unavailable(Exception):
    """Go or the pinned buf cannot run here; the check is skipped."""


def buf_command(root: Path) -> list[str]:
    """`go run` of the buf release build-config.env pins."""
    version = build_config(root / "build-config.env").get("BUF_VERSION", "")
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise SystemExit("proto_generate: build-config.env needs BUF_VERSION as X.Y.Z")
    return ["go", "run", f"{BUF_MODULE}@v{version}"]


def run(cmd: list[str], root: Path) -> subprocess.CompletedProcess[str]:
    """Run one tool in the repository root, bounded by TOOL_TIMEOUT_S."""
    try:
        return subprocess.run(  # noqa: S603 (fixed argv: go and the pinned buf)
            cmd, cwd=root, capture_output=True, text=True, timeout=TOOL_TIMEOUT_S, check=False
        )
    except FileNotFoundError as exc:
        raise Unavailable(f"{cmd[0]} is not installed: {exc}") from exc


def ready(buf: list[str], root: Path) -> None:
    """Fetch and build buf once; refuse with a reason when that fails."""
    out = run([*buf, "--version"], root)
    if out.returncode != 0:
        raise Unavailable(f"cannot run {' '.join(buf)}: {out.stderr.strip()[-400:]}")


def generate(buf: list[str], root: Path, scratch: Path) -> dict[str, str]:
    """Run buf generate and the proofs into scratch; return {path: text}."""
    out = run([*buf, "generate", "--output", str(scratch)], root)
    if out.returncode != 0:
        raise SystemExit(f"proto_generate: buf generate failed:\n{out.stderr}")
    proofs = run([sys.executable, str(root / POSTPROCESS), "--root", str(scratch)], root)
    if proofs.returncode != 0:
        raise SystemExit(f"proto_generate: {POSTPROCESS} failed:\n{proofs.stderr}")
    return {
        p.relative_to(scratch).as_posix(): p.read_text(encoding="utf-8")
        for p in sorted((scratch / GENERATED).rglob("*.pb.go"))
    }


def committed(root: Path) -> dict[str, str]:
    """The *.pb.go files the tree holds."""
    return {
        p.relative_to(root).as_posix(): p.read_text(encoding="utf-8")
        for p in sorted((root / GENERATED).rglob("*.pb.go"))
    }


def differences(want: dict[str, str], have: dict[str, str]) -> list[str]:
    """Paths that are missing, stale or different."""
    out = [f"missing: {p}" for p in sorted(want.keys() - have.keys())]
    out += [f"stale: {p}" for p in sorted(have.keys() - want.keys())]
    out += [f"differs: {p}" for p in sorted(want.keys() & have.keys()) if want[p] != have[p]]
    return out


def write(root: Path, want: dict[str, str], have: dict[str, str]) -> None:
    """Make gen/go hold exactly the generated *.pb.go files."""
    for path in have.keys() - want.keys():
        (root / path).unlink()
    for path, text in want.items():
        (root / path).parent.mkdir(parents=True, exist_ok=True)
        (root / path).write_text(text, encoding="utf-8")


def lint(buf: list[str], root: Path) -> list[str]:
    out = run([*buf, "lint"], root)
    return [] if out.returncode == 0 else [f"buf lint: {line}" for line in out.stdout.splitlines()]


def breaking(buf: list[str], root: Path, ref: str) -> list[str]:
    out = run([*buf, "breaking", "--against", f".git#ref={ref}"], root)
    if out.returncode == 0:
        return []
    return [
        f"buf breaking against {ref}: {line}" for line in (out.stdout + out.stderr).splitlines()
    ]


def check_all(buf: list[str], root: Path, mode: str, against: str | None) -> list[str]:
    """Lint, generate, compare (or write), and optionally check breaking changes."""
    problems = lint(buf, root)
    with tempfile.TemporaryDirectory(prefix="proto-") as tmp:
        want = generate(buf, root, Path(tmp))
    have = committed(root)
    if mode == "write":
        write(root, want, have)
    else:
        problems += differences(want, have)
    if against:
        problems += breaking(buf, root, against)
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate gen/go in place")
    group.add_argument("--check", action="store_true", help="fail on any difference")
    parser.add_argument("--breaking-against", metavar="REF", help="also run buf breaking")
    parser.add_argument("--root", type=Path, default=REPO, help="repository root")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    mode = "write" if args.write else "check"
    try:
        buf = buf_command(root)
        ready(buf, root)
        problems = check_all(buf, root, mode, args.breaking_against)
    except Unavailable as exc:
        if mode == "check":
            print(f"proto_generate: SKIP: {exc}")
            return SKIP
        raise SystemExit(f"proto_generate: {exc}") from exc
    for line in problems:
        print(f"proto_generate: {line}")
    if problems:
        print("proto_generate: run python3 scripts/codegen/vmafx-api.py --write, then")
        print("  python3 scripts/codegen/proto_generate.py --write (never edit generated files)")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
